import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Row = Record<string, any>;
type Field = { key:string; label:string; type?:'text'|'number'|'date'|'select'|'textarea'|'checkbox'; required?:boolean; options?:string[]; ref?:string; step?:string };
type Module = { key:string; label:string; icon:string; desc:string; fields:Field[]; print?:'invoice'|'transport'|'offer' };
const money = (n:any) => new Intl.NumberFormat('hr-HR',{style:'currency',currency:'EUR'}).format(Number(n||0));
const date = (d:any) => d ? new Date(d).toLocaleDateString('hr-HR') : '—';
const tokenKey='adriatms_token';
async function api(path:string, opts:any={}){
  const token = localStorage.getItem(tokenKey);
  const res = await fetch('/api'+path, { ...opts, headers:{ 'Content-Type':'application/json', ...(token?{Authorization:'Bearer '+token}:{}), ...(opts.headers||{}) }});
  const data = await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.error || 'API greška'); return data;
}

const modules:Module[] = [
 {key:'trucks',label:'Kamioni',icon:'🚚',desc:'Vozni park, registracije, potrošnja i statusi.',fields:[{key:'plate',label:'Registracija',required:true},{key:'brand',label:'Marka'},{key:'model',label:'Model'},{key:'year',label:'Godina',type:'number'},{key:'vin',label:'VIN'},{key:'euro_class',label:'EURO klasa',type:'select',options:['EURO 5','EURO 6','EURO 7']},{key:'fuel_type',label:'Gorivo',type:'select',options:['Diesel','LNG','CNG','Električni']},{key:'avg_consumption',label:'Prosj. l/100km',type:'number',step:'0.1'},{key:'tank_liters',label:'Spremnik L',type:'number'},{key:'odometer_km',label:'Kilometri',type:'number'},{key:'status',label:'Status',type:'select',options:['active','service','inactive']},{key:'registration_until',label:'Registracija do',type:'date'},{key:'insurance_until',label:'Osiguranje do',type:'date'}]},
 {key:'drivers',label:'Vozači',icon:'🧑‍✈️',desc:'Vozači, dozvole, tahograf kartice i liječnički.',fields:[{key:'name',label:'Ime i prezime',required:true},{key:'phone',label:'Telefon'},{key:'email',label:'Email'},{key:'license_no',label:'Broj dozvole'},{key:'license_until',label:'Dozvola do',type:'date'},{key:'card_no',label:'Tahograf kartica'},{key:'card_until',label:'Kartica do',type:'date'},{key:'adr_until',label:'ADR do',type:'date'},{key:'medical_until',label:'Liječnički do',type:'date'},{key:'base_salary',label:'Osnovica plaće',type:'number'},{key:'status',label:'Status',type:'select',options:['active','vacation','inactive']} ]},
 {key:'trailers',label:'Prikolice',icon:'🚛',desc:'Poluprikolice, nosivost, volumen i registracija.',fields:[{key:'plate',label:'Registracija',required:true},{key:'type',label:'Tip',type:'select',options:['cerada','hladnjača','cisterna','kiper','platforma']},{key:'capacity_kg',label:'Nosivost kg',type:'number'},{key:'volume_m3',label:'Volumen m³',type:'number'},{key:'registration_until',label:'Registracija do',type:'date'},{key:'status',label:'Status',type:'select',options:['active','service','inactive']} ]},
 {key:'customers',label:'Kupci',icon:'🏢',desc:'CRM kupaca, uvjeti plaćanja i podaci za račune.',fields:[{key:'name',label:'Naziv',required:true},{key:'oib',label:'OIB'},{key:'vat_id',label:'VAT ID'},{key:'email',label:'Email'},{key:'phone',label:'Telefon'},{key:'address',label:'Adresa'},{key:'city',label:'Grad'},{key:'country',label:'Država'},{key:'payment_days',label:'Valuta plaćanja dana',type:'number'}]},
 {key:'suppliers',label:'Dobavljači',icon:'🏭',desc:'Dobavljači goriva, servisa, dijelova i podizvođača.',fields:[{key:'name',label:'Naziv',required:true},{key:'oib',label:'OIB'},{key:'email',label:'Email'},{key:'phone',label:'Telefon'},{key:'address',label:'Adresa'},{key:'city',label:'Grad'},{key:'country',label:'Država'},{key:'category',label:'Kategorija',type:'select',options:['gorivo','servis','gume','cestarina','podizvođač','ostalo']},{key:'payment_days',label:'Valuta plaćanja',type:'number'}]},
 {key:'routes',label:'Rute',icon:'🗺️',desc:'Izračun udaljenosti, goriva, zakonskih pauza i mjesta odmora.',fields:[{key:'name',label:'Naziv',required:true},{key:'origin',label:'Polazište',required:true},{key:'destination',label:'Odredište',required:true},{key:'via',label:'Preko / via'},{key:'distance_km',label:'Udaljenost km',type:'number'},{key:'duration_h',label:'Trajanje h',type:'number'},{key:'fuel_liters',label:'Gorivo L',type:'number'},{key:'toll_estimate',label:'Cestarina procjena',type:'number'}]},
 {key:'transports',label:'Dispečing / prijevozi',icon:'📦',desc:'Planiranje prijevoza, tereti, vozila, vozači i putni nalog.',print:'transport',fields:[{key:'order_no',label:'Putni nalog',required:true},{key:'customer_id',label:'Kupac',ref:'customers'},{key:'truck_id',label:'Kamion',ref:'trucks'},{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'trailer_id',label:'Prikolica',ref:'trailers'},{key:'route_id',label:'Ruta',ref:'routes'},{key:'status',label:'Status',type:'select',options:['planned','loading','in_transit','delivered','invoiced','cancelled']},{key:'load_date',label:'Datum utovara',type:'date'},{key:'unload_date',label:'Datum istovara',type:'date'},{key:'loading_place',label:'Mjesto utovara'},{key:'unloading_place',label:'Mjesto istovara'},{key:'cargo_desc',label:'Teret',type:'textarea'},{key:'cargo_weight_kg',label:'Težina kg',type:'number'},{key:'price',label:'Cijena',type:'number'},{key:'currency',label:'Valuta',type:'select',options:['EUR','HRK','USD']},{key:'notes',label:'Napomene',type:'textarea'}]},
 {key:'expenses',label:'Troškovi vozača',icon:'💳',desc:'Dnevnice, parking, cestarine, ostali troškovi.',fields:[{key:'transport_id',label:'Prijevoz',ref:'transports'},{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'supplier_id',label:'Dobavljač',ref:'suppliers'},{key:'type',label:'Tip',type:'select',options:['dnevnica','parking','cestarina','pranje','popravak','ostalo'],required:true},{key:'amount',label:'Iznos',type:'number',required:true},{key:'currency',label:'Valuta',type:'select',options:['EUR','HRK','USD']},{key:'expense_date',label:'Datum',type:'date'},{key:'description',label:'Opis',type:'textarea'},{key:'paid',label:'Plaćeno',type:'checkbox'}]},
 {key:'fuel_entries',label:'Gorivo',icon:'⛽',desc:'Tankiranja, cijena po litri i potrošnja.',fields:[{key:'truck_id',label:'Kamion',ref:'trucks'},{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'entry_date',label:'Datum',type:'date'},{key:'liters',label:'Litara',type:'number',required:true},{key:'price_per_liter',label:'Cijena/L',type:'number',step:'0.001',required:true},{key:'odometer_km',label:'Kilometri',type:'number'},{key:'station',label:'Postaja'},{key:'country',label:'Država'}]},
 {key:'service_records',label:'Servisi',icon:'🛠️',desc:'Servisi, gume, preventivno održavanje i rokovi.',fields:[{key:'truck_id',label:'Kamion',ref:'trucks'},{key:'service_date',label:'Datum',type:'date'},{key:'type',label:'Tip'},{key:'odometer_km',label:'Kilometri',type:'number'},{key:'amount',label:'Iznos',type:'number'},{key:'supplier_id',label:'Dobavljač',ref:'suppliers'},{key:'description',label:'Opis',type:'textarea'},{key:'next_service_date',label:'Sljedeći datum',type:'date'},{key:'next_service_km',label:'Sljedeći km',type:'number'}]},
 {key:'gps_positions',label:'GPS live',icon:'📍',desc:'Live pozicije vozila, brzina, smjer i karta flote bez vanjskih servisa.',fields:[{key:'truck_id',label:'Kamion',ref:'trucks'},{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'position_time',label:'Vrijeme pozicije',type:'date'},{key:'lat',label:'Latitude',type:'number',required:true,step:'0.000001'},{key:'lng',label:'Longitude',type:'number',required:true,step:'0.000001'},{key:'speed_kmh',label:'Brzina km/h',type:'number'},{key:'heading',label:'Smjer °',type:'number'},{key:'ignition',label:'Kontakt uključen',type:'checkbox'},{key:'source',label:'Izvor',type:'select',options:['manual','mobile','tracker','import']},{key:'note',label:'Napomena',type:'textarea'}]},
 {key:'tachograph_entries',label:'Tahograf',icon:'⏱️',desc:'Radna vremena, vožnja, odmori i automatska upozorenja na EU/RH pravila.',fields:[{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'truck_id',label:'Kamion',ref:'trucks'},{key:'entry_date',label:'Datum',type:'date',required:true},{key:'drive_minutes',label:'Vožnja min',type:'number'},{key:'work_minutes',label:'Rad min',type:'number'},{key:'rest_minutes',label:'Odmor min',type:'number'},{key:'availability_minutes',label:'Raspoloživost min',type:'number'},{key:'note',label:'Napomena',type:'textarea'}]},
 {key:'payrolls',label:'Plaće',icon:'💶',desc:'Obračun plaća vozača, dnevnice, bonusi, odbici i status isplate.',fields:[{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'period_month',label:'Period YYYY-MM',required:true},{key:'base_salary',label:'Osnovica',type:'number'},{key:'per_diem',label:'Dnevnice',type:'number'},{key:'bonuses',label:'Bonusi',type:'number'},{key:'deductions',label:'Odbici',type:'number'},{key:'gross_total',label:'Bruto ukupno',type:'number'},{key:'net_total',label:'Neto procjena',type:'number'},{key:'status',label:'Status',type:'select',options:['draft','approved','paid']},{key:'note',label:'Napomena',type:'textarea'}]},
 {key:'cmr_documents',label:'CMR',icon:'📋',desc:'CMR dokumenti s pošiljateljem, primateljem, teretom i PDF ispisom.',print:'transport',fields:[{key:'transport_id',label:'Prijevoz',ref:'transports'},{key:'cmr_no',label:'CMR broj',required:true},{key:'sender',label:'Pošiljatelj'},{key:'consignee',label:'Primatelj'},{key:'carrier',label:'Prijevoznik'},{key:'pickup_place',label:'Mjesto preuzimanja'},{key:'delivery_place',label:'Mjesto isporuke'},{key:'goods_desc',label:'Opis robe',type:'textarea'},{key:'packages',label:'Pakiranja'},{key:'gross_weight_kg',label:'Bruto kg',type:'number'},{key:'instructions',label:'Upute',type:'textarea'},{key:'status',label:'Status',type:'select',options:['draft','issued','signed','archived']} ]},

 {key:'invoices',label:'Fakture',icon:'🧾',desc:'Računi kupcima, PDV, status naplate i PDF ispis.',print:'invoice',fields:[{key:'invoice_no',label:'Broj računa',required:true},{key:'customer_id',label:'Kupac',ref:'customers'},{key:'transport_id',label:'Prijevoz',ref:'transports'},{key:'issue_date',label:'Datum izdavanja',type:'date'},{key:'due_date',label:'Dospijeće',type:'date'},{key:'status',label:'Status',type:'select',options:['draft','sent','paid','overdue','cancelled']},{key:'subtotal',label:'Osnovica',type:'number'},{key:'vat_rate',label:'PDV %',type:'number'},{key:'vat_amount',label:'PDV iznos',type:'number'},{key:'total',label:'Ukupno',type:'number'},{key:'currency',label:'Valuta',type:'select',options:['EUR','HRK','USD']},{key:'notes',label:'Napomene',type:'textarea'}]},
 {key:'offers',label:'Ponude',icon:'📄',desc:'Komercijalne ponude i pretvaranje u prijevoz.',print:'offer',fields:[{key:'offer_no',label:'Broj ponude',required:true},{key:'customer_id',label:'Kupac',ref:'customers'},{key:'issue_date',label:'Datum',type:'date'},{key:'valid_until',label:'Vrijedi do',type:'date'},{key:'status',label:'Status',type:'select',options:['draft','sent','accepted','rejected']},{key:'route_desc',label:'Ruta/opis',type:'textarea'},{key:'price',label:'Cijena',type:'number'},{key:'currency',label:'Valuta',type:'select',options:['EUR','HRK','USD']},{key:'notes',label:'Napomene',type:'textarea'}]},
 {key:'documents',label:'Dokumenti / CMR',icon:'📚',desc:'CMR, police, certifikati i datumi isteka.',fields:[{key:'entity',label:'Entitet',type:'select',options:['truck','driver','transport','customer','company']},{key:'entity_id',label:'ID entiteta'},{key:'doc_type',label:'Tip',type:'select',options:['CMR','registracija','polica','licenca','ugovor','ostalo'],required:true},{key:'title',label:'Naziv',required:true},{key:'file_url',label:'URL/datoteka'},{key:'expires_at',label:'Ističe',type:'date'}]},
 {key:'notifications',label:'Notifikacije',icon:'🔔',desc:'Rokovi, upozorenja i operativne obavijesti.',fields:[{key:'title',label:'Naslov',required:true},{key:'body',label:'Poruka',type:'textarea'},{key:'severity',label:'Prioritet',type:'select',options:['info','warning','danger','success']},{key:'read_at',label:'Pročitano',type:'date'}]},
 {key:'app_settings',label:'Postavke',icon:'⚙️',desc:'Postavke tvrtke, numeracije, PDV-a, dokumenata i operativnih pravila.',fields:[{key:'setting_key',label:'Ključ postavke',required:true},{key:'setting_value',label:'JSON vrijednost',type:'textarea',required:true}]}
];
const specialViews = [{key:'analytics',label:'📈 Analitika'},{key:'backup',label:'💾 Backup'},{key:'admin',label:'👥 Administracija'},{key:'pdf',label:'🖨️ PDF centar'},{key:'excel',label:'📊 Excel centar'},{key:'features150',label:'🧩 150 funkcija'}];

const cities:Record<string,[number,number]>={Zagreb:[45.815,15.982],Rijeka:[45.327,14.442],Split:[43.508,16.44],Osijek:[45.555,18.695],Zadar:[44.119,15.232],Pula:[44.866,13.849],Dubrovnik:[42.65,18.094],Ljubljana:[46.056,14.505],Maribor:[46.554,15.645],Graz:[47.07,15.439],Vienna:[48.208,16.373],Budapest:[47.497,19.04],Belgrade:[44.812,20.461],Sarajevo:[43.856,18.413],Munich:[48.135,11.582],Milan:[45.464,9.19],Trieste:[45.65,13.77],Venice:[45.44,12.315],Prague:[50.075,14.438],Warsaw:[52.229,21.012],Bratislava:[48.148,17.107],Frankfurt:[50.11,8.682],Hamburg:[53.551,9.993],Rotterdam:[51.924,4.477],Paris:[48.857,2.352]};
const stops=[['Ravna Gora',45.37,14.94],['Zir',44.33,15.68],['Spačva',45.03,18.92],['Plitvice',44.88,15.62],['Lučko',45.75,15.88],['Sežana',45.71,13.87],['Graz West',47.04,15.36],['Nickelsdorf',47.94,17.07],['Letenye',46.43,16.72],['Ljubljana Barje',46.02,14.46],['München Ost',48.13,11.7],['Trieste Fernetti',45.71,13.81],['Beograd Šimanovci',44.87,20.09]];
function hav(a:[number,number],b:[number,number]){const R=6371, dLat=(b[0]-a[0])*Math.PI/180, dLon=(b[1]-a[1])*Math.PI/180; const x=Math.sin(dLat/2)**2+Math.cos(a[0]*Math.PI/180)*Math.cos(b[0]*Math.PI/180)*Math.sin(dLon/2)**2; return 2*R*Math.asin(Math.sqrt(x));}
function routeCalc(origin:string,destination:string,via:string,cons=30){ const pts=[origin, ...(via?via.split(',').map(s=>s.trim()).filter(Boolean):[]), destination].map(x=>cities[x]).filter(Boolean) as [number,number][]; let km=0; for(let i=1;i<pts.length;i++) km += hav(pts[i-1],pts[i])*1.22; const h=km/68; const rests=[]; for(let t=4.5;t<h;t+=5.25) rests.push({atHour:t, breakMin:t+0.75<h?45:0, rule:'EU 561/2006: nakon najviše 4h30 vožnje obvezna pauza 45 min'}); const near=stops.map(s=>({name:s[0] as string, kmFromRoute: pts[0]?Math.min(...pts.map(p=>hav(p,[s[1] as number,s[2] as number]))):999})).sort((a,b)=>a.kmFromRoute-b.kmFromRoute).slice(0,5); return {distance_km:+km.toFixed(1), duration_h:+h.toFixed(2), fuel_liters:+(km*cons/100).toFixed(1), toll_estimate:+(km*0.18).toFixed(2), rest_plan:rests, stops:near}; }
function MiniMap({origin,destination,via}:{origin:string;destination:string;via?:string}){ const names=[origin,...(via?via.split(',').map(x=>x.trim()).filter(Boolean):[]),destination].filter(x=>cities[x]); const pts=names.map(n=>cities[n]); if(pts.length<2) return <div className="mapEmpty">Unesite gradove iz liste: {Object.keys(cities).slice(0,12).join(', ')}...</div>; const lats=pts.map(p=>p[0]), lons=pts.map(p=>p[1]); const minLat=Math.min(...lats), maxLat=Math.max(...lats), minLon=Math.min(...lons), maxLon=Math.max(...lons); const xy=(p:[number,number])=>[40+((p[1]-minLon)/(maxLon-minLon||1))*520,260-(40+((p[0]-minLat)/(maxLat-minLat||1))*180)]; const line=pts.map(p=>xy(p).join(',')).join(' '); return <svg className="map" viewBox="0 0 600 300"><defs><linearGradient id="g" x1="0" x2="1"><stop stopColor="#0ea5e9"/><stop offset="1" stopColor="#22c55e"/></linearGradient></defs><rect width="600" height="300" rx="20" fill="var(--map)"/><polyline points={line} fill="none" stroke="url(#g)" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round"/>{pts.map((p,i)=>{const [x,y]=xy(p);return <g key={i}><circle cx={x} cy={y} r="9" fill={i===0?'#22c55e':i===pts.length-1?'#ef4444':'#f59e0b'}/><text x={x+12} y={y-10} fill="currentColor" fontSize="13">{names[i]}</text></g>})}</svg> }
function nameOf(ref:string|undefined,id:any,refs:Record<string,Row[]>){ if(!ref||!id) return '—'; const r=refs[ref]?.find(x=>x.id===id); return r?.name || r?.plate || r?.order_no || r?.invoice_no || r?.offer_no || id?.slice?.(0,8) || '—'; }

function App(){
 const [token,setToken]=useState(localStorage.getItem(tokenKey)); const [user,setUser]=useState<any>(null); const [company,setCompany]=useState<any>(null); const [view,setView]=useState('dashboard'); const [theme,setTheme]=useState(localStorage.getItem('theme')||'light'); const [toast,setToast]=useState('');
 useEffect(()=>{document.documentElement.dataset.theme=theme; localStorage.setItem('theme',theme)},[theme]);
 useEffect(()=>{ if(token) api('/me').then(d=>{setUser(d.user);setCompany(d.company)}).catch(()=>logout()); },[token]);
 function logout(){localStorage.removeItem(tokenKey);setToken(null);setUser(null);}
 if(!token) return <Auth onLogin={(t:string,u:any,c:any)=>{localStorage.setItem(tokenKey,t);setToken(t);setUser(u);setCompany(c)}} setToast={setToast} toast={toast}/>;
 const mod=modules.find(m=>m.key===view);
 return <div className="shell"><aside><div className="brand"><b>AdriaTMS</b><span>ERP za prijevoznike</span></div><button className={view==='dashboard'?'sel':''} onClick={()=>setView('dashboard')}>📊 Dashboard</button>{modules.map(m=><button key={m.key} className={view===m.key?'sel':''} onClick={()=>setView(m.key)}>{m.icon} {m.label}</button>)}{specialViews.map(v=><button key={v.key} className={view===v.key?'sel':''} onClick={()=>setView(v.key)}>{v.label}</button>)}<div className="muted block">Svi moduli iz specifikacije su aktivni: Dashboard, flota, GPS, tahograf, financije, PDF/Excel, analitika, backup, postavke, administracija i 150 poslovnih funkcija.</div></aside><main><header><div><h1>{mod?mod.label:'Dashboard'}</h1><p>{mod?mod.desc:'Pregled flote, prihoda, troškova i rokova.'}</p></div><div className="headerActions"><span className="pill">{company?.name}</span><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☀️':'🌙'}</button><button onClick={logout}>Odjava</button></div></header>{toast&&<div className="toast" onClick={()=>setToast('')}>{toast}</div>}{view==='dashboard'?<Dashboard setView={setView}/>:view==='analytics'?<Analytics/>:view==='backup'?<Backup setToast={setToast}/>:view==='admin'?<Admin setToast={setToast}/>:view==='pdf'?<PdfCenter/>:view==='excel'?<ExcelCenter/>:view==='features150'?<Features150 setToast={setToast}/>:mod?<ModuleView module={mod} setToast={setToast}/>:<Dashboard setView={setView}/>}</main></div>
}
function Auth({onLogin,setToast,toast}:any){ const [mode,setMode]=useState<'login'|'register'>('login'); const [f,setF]=useState<any>({country:'HR'}); const [busy,setBusy]=useState(false); async function submit(e:any){ e.preventDefault(); setBusy(true); try{ const d= await api('/auth/'+mode,{method:'POST',body:JSON.stringify(f)}); onLogin(d.token,d.user,d.company);}catch(e:any){setToast(e.message)} finally{setBusy(false)} } async function setup(){ try{setBusy(true); await api('/setup',{method:'POST'}); setToast('Baza je inicijalizirana. Sada se možete registrirati.')}catch(e:any){setToast(e.message)}finally{setBusy(false)} }
 return <div className="auth"><div className="authCard"><h1>AdriaTMS ERP</h1><p>Standalone Netlify + Neon aplikacija za transport, flotu, fakture i operativu.</p>{toast&&<div className="toast">{toast}</div>}<div className="tabs"><button className={mode==='login'?'sel':''} onClick={()=>setMode('login')}>Prijava</button><button className={mode==='register'?'sel':''} onClick={()=>setMode('register')}>Registracija tvrtke</button></div><form onSubmit={submit}>{mode==='register'&&<><input required placeholder="Naziv tvrtke" onChange={e=>setF({...f,companyName:e.target.value})}/><input required placeholder="OIB tvrtke" onChange={e=>setF({...f,oib:e.target.value})}/><input required placeholder="Vaše ime" onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Adresa" onChange={e=>setF({...f,address:e.target.value})}/><input placeholder="Grad" onChange={e=>setF({...f,city:e.target.value})}/></>} {mode==='login'||mode==='register'?<><input required type="email" placeholder="Email" onChange={e=>setF({...f,email:e.target.value})}/><input required type="password" placeholder="Lozinka" onChange={e=>setF({...f,password:e.target.value})}/></>:null}<button disabled={busy}>{busy?'Radim...':mode==='login'?'Prijavi se':'Registriraj tvrtku'}</button></form><button className="ghost" onClick={setup}>Prvi put? Inicijaliziraj Neon bazu</button><small>Sigurnost: lozinke se spremaju kao bcrypt hash, sesija je JWT, podaci su odvojeni po company_id.</small></div></div> }
function Dashboard({setView}:any){ const [d,setD]=useState<any>(null); useEffect(()=>{api('/dashboard').then(setD)},[]); if(!d) return <div className="grid"><div className="card">Učitavanje...</div></div>; const revenue=(d.transports||[]).reduce((s:any,x:any)=>s+Number(x.total||0),0); const invTotal=(d.invoices||[]).reduce((s:any,x:any)=>s+Number(x.total||0),0); return <><div className="kpis"><K label="Kamioni" val={d.trucks}/><K label="Vozači" val={d.drivers}/><K label="Prihod prijevoza" val={money(revenue)}/><K label="Fakturirano" val={money(invTotal)}/><K label="Gorivo mj." val={money(d.monthlyFuel.total)}/><K label="Troškovi mj." val={money(d.monthlyExpenses+d.monthlyService)}/></div><div className="grid two"><div className="card"><h3>Status prijevoza</h3>{(d.transports||[]).map((x:any)=><div className="row" key={x.status}><b>{x.status}</b><span>{x.n} · {money(x.total)}</span></div>)}<button onClick={()=>setView('transports')}>Otvori dispečing</button></div><div className="card"><h3>Upozorenja rokova</h3>{d.alerts?.length?d.alerts.map((a:any,i:number)=><div className="alert" key={i}>{a.type}: <b>{a.label}</b> do {date(a.due)}</div>):<p className="muted">Nema rokova u sljedećih 30 dana.</p>}</div></div><div className="card"><h3>Što je implementirano</h3><p>CRUD, validacije, role-permissions, audit log, izračun ruta/goriva/pauza, offline karta, preporuke odmorišta, putni nalog, fakture/ponude s ispisom u PDF kroz browser print, CSV/Excel izvoz, dashboard i responsive dark/light UI.</p></div></> }
function K({label,val}:any){return <div className="kpi"><span>{label}</span><b>{val}</b></div>}
function ModuleView({module,setToast}:{module:Module;setToast:(s:string)=>void}){ const [rows,setRows]=useState<Row[]>([]), [refs,setRefs]=useState<Record<string,Row[]>>({}), [edit,setEdit]=useState<Row|null>(null), [search,setSearch]=useState(''); const [route,setRoute]=useState<any>(null); const refNames=Array.from(new Set(module.fields.map(f=>f.ref).filter(Boolean))) as string[]; async function load(){ const [r,...rr]=await Promise.all([api('/'+module.key+'?search='+encodeURIComponent(search)),...refNames.map(x=>api('/'+x))]); setRows(r); const obj:any={}; refNames.forEach((n,i)=>obj[n]=rr[i]); setRefs(obj); }
 useEffect(()=>{load().catch(e=>setToast(e.message))},[module.key]); async function save(data:Row){ try{ if(module.key==='invoices'){data.vat_amount=+(Number(data.subtotal||0)*Number(data.vat_rate||25)/100).toFixed(2); data.total=+(Number(data.subtotal||0)+data.vat_amount).toFixed(2)} if(module.key==='routes'){data.rest_plan=route?.rest_plan||data.rest_plan}
      if(module.key==='app_settings' && typeof data.setting_value==='string'){try{data.setting_value=JSON.parse(data.setting_value)}catch{throw new Error('Postavka mora biti valjani JSON, npr. {"pdv":25}')}} await api('/'+module.key+(data.id?'/'+data.id:''),{method:data.id?'PUT':'POST',body:JSON.stringify(data)}); setEdit(null); await load(); setToast('Spremljeno.')}catch(e:any){setToast(e.message)} }
 async function del(id:string){ if(confirm('Obrisati zapis?')) try{await api('/'+module.key+'/'+id,{method:'DELETE'}); await load(); setToast('Obrisano.')}catch(e:any){setToast(e.message)} }
 async function next(){ const kind=module.key==='invoices'?'invoice':module.key==='offers'?'offer':'transport'; const n=await api('/next-number/'+kind); setEdit({...(edit||{}), [module.key==='invoices'?'invoice_no':module.key==='offers'?'offer_no':'order_no']:n.number}); }
 function exportCsv(){ const csv=[Object.keys(rows[0]||{}).join(';'),...rows.map(r=>Object.values(r).map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';'))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download=module.key+'.csv'; a.click(); }
 return <><div className="toolbar"><input placeholder="Pretraži..." value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load()}}/><button onClick={load}>Traži</button><button onClick={()=>setEdit({})}>+ Novi zapis</button>{['transports','invoices','offers'].includes(module.key)&&<button onClick={next}>Sljedeći broj</button>}<button onClick={exportCsv}>Excel/CSV</button></div>{module.key==='routes'&&<RoutePanel onCalc={setRoute}/>}<div className="card tableWrap"><table><thead><tr>{module.fields.slice(0,7).map(f=><th key={f.key}>{f.label}</th>)}<th>Akcije</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{module.fields.slice(0,7).map(f=><td key={f.key}>{f.ref?nameOf(f.ref,r[f.key],refs):f.type==='checkbox'?(r[f.key]?'Da':'Ne'):String(r[f.key]??'—')}</td>)}<td><button onClick={()=>setEdit(r)}>Uredi</button>{module.print&&<button onClick={()=>printDoc(module.print!,r,refs)}>PDF</button>}<button className="danger" onClick={()=>del(r.id)}>Briši</button></td></tr>)}</tbody></table>{!rows.length&&<p className="muted center">Nema zapisa.</p>}</div>{edit&&<Form module={module} row={edit} refs={refs} route={route} onClose={()=>setEdit(null)} onSave={save}/>}</> }
function RoutePanel({onCalc}:any){ const [f,setF]=useState<any>({origin:'Zagreb',destination:'Split',via:'',cons:30}); const r=useMemo(()=>routeCalc(f.origin,f.destination,f.via,Number(f.cons||30)),[f]); useEffect(()=>onCalc(r),[r.distance_km,r.duration_h,r.fuel_liters]); return <div className="grid two"><div className="card"><h3>Kalkulator rute i zakonskih pauza</h3><div className="formGrid"><select value={f.origin} onChange={e=>setF({...f,origin:e.target.value})}>{Object.keys(cities).map(c=><option key={c}>{c}</option>)}</select><select value={f.destination} onChange={e=>setF({...f,destination:e.target.value})}>{Object.keys(cities).map(c=><option key={c}>{c}</option>)}</select><input placeholder="Via, odvojeno zarezom" value={f.via} onChange={e=>setF({...f,via:e.target.value})}/><input type="number" value={f.cons} onChange={e=>setF({...f,cons:e.target.value})}/></div><div className="kpis small"><K label="km" val={r.distance_km}/><K label="sati" val={r.duration_h}/><K label="gorivo L" val={r.fuel_liters}/><K label="cestarina" val={money(r.toll_estimate)}/></div><h4>Pauze</h4>{r.rest_plan.length?r.rest_plan.map((x:any,i:number)=><p key={i}>Nakon {x.atHour}h: pauza {x.breakMin} min</p>):<p>Nema obvezne pauze za kratku rutu.</p>}<h4>Preporučena odmorišta</h4>{r.stops.map((s:any)=><span className="pill" key={s.name}>{s.name}</span>)}</div><div className="card"><MiniMap origin={f.origin} destination={f.destination} via={f.via}/></div></div> }
function Form({module,row,refs,route,onClose,onSave}:any){ const [f,setF]=useState<Row>(row); useEffect(()=>{ if(module.key==='routes'&&route) setF((x:Row)=>({...x, distance_km:route.distance_km,duration_h:route.duration_h,fuel_liters:route.fuel_liters,toll_estimate:route.toll_estimate,rest_plan:route.rest_plan})); },[route]); return <div className="modal"><form className="modalCard" onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="modalHead"><h2>{row.id?'Uredi':'Novi'} · {module.label}</h2><button type="button" onClick={onClose}>✕</button></div><div className="formGrid">{module.fields.map((field:Field)=><label key={field.key}>{field.label}{field.ref?<select value={f[field.key]||''} onChange={e=>setF({...f,[field.key]:e.target.value||null})}><option value="">—</option>{refs[field.ref]?.map((r:Row)=><option key={r.id} value={r.id}>{r.name||r.plate||r.order_no||r.invoice_no}</option>)}</select>:field.type==='textarea'?<textarea required={field.required} value={f[field.key]||''} onChange={e=>setF({...f,[field.key]:e.target.value})}/>:field.type==='select'?<select required={field.required} value={f[field.key]||''} onChange={e=>setF({...f,[field.key]:e.target.value})}><option value="">—</option>{field.options?.map(o=><option key={o}>{o}</option>)}</select>:field.type==='checkbox'?<input type="checkbox" checked={!!f[field.key]} onChange={e=>setF({...f,[field.key]:e.target.checked})}/>:<input required={field.required} type={field.type||'text'} step={field.step||'0.01'} value={f[field.key]??''} onChange={e=>setF({...f,[field.key]:e.target.value})}/>}</label>)}</div><div className="modalActions"><button type="button" onClick={onClose}>Odustani</button><button>Spremi</button></div></form></div> }
function printDoc(kind:string,r:Row,refs:Record<string,Row[]>){ const customer=nameOf('customers',r.customer_id,refs), transport=nameOf('transports',r.transport_id,refs), truck=nameOf('trucks',r.truck_id,refs), driver=nameOf('drivers',r.driver_id,refs); let title=kind==='invoice'?'RAČUN':kind==='offer'?'PONUDA':'PUTNI NALOG'; let html=`<html><head><title>${title}</title><style>body{font-family:Arial;padding:36px;color:#111}h1{color:#0f766e}table{width:100%;border-collapse:collapse;margin-top:20px}td,th{border:1px solid #ddd;padding:10px}.right{text-align:right}.muted{color:#666}</style></head><body><h1>${title}</h1><p class="muted">Generirano iz AdriaTMS ERP</p>`; if(kind==='invoice') html+=`<h2>${r.invoice_no}</h2><p>Kupac: <b>${customer}</b></p><p>Datum: ${date(r.issue_date)} · Dospijeće: ${date(r.due_date)}</p><table><tr><th>Opis</th><th class="right">Osnovica</th><th>PDV</th><th class="right">Ukupno</th></tr><tr><td>Prijevoz ${transport}</td><td class="right">${money(r.subtotal)}</td><td>${r.vat_rate}% (${money(r.vat_amount)})</td><td class="right"><b>${money(r.total)}</b></td></tr></table><p>${r.notes||''}</p>`; else if(kind==='transport') html+=`<h2>${r.order_no}</h2><table><tr><td>Kupac</td><td>${customer}</td></tr><tr><td>Vozilo</td><td>${truck}</td></tr><tr><td>Vozač</td><td>${driver}</td></tr><tr><td>Utovar</td><td>${r.loading_place} · ${date(r.load_date)}</td></tr><tr><td>Istovar</td><td>${r.unloading_place} · ${date(r.unload_date)}</td></tr><tr><td>Teret</td><td>${r.cargo_desc} (${r.cargo_weight_kg||0} kg)</td></tr></table><p>Potpis disponenta: ____________________ Potpis vozača: ____________________</p>`; else html+=`<h2>${r.offer_no}</h2><p>Kupac: ${customer}</p><p>Vrijedi do: ${date(r.valid_until)}</p><table><tr><th>Opis</th><th class="right">Cijena</th></tr><tr><td>${r.route_desc||'Usluga prijevoza'}</td><td class="right">${money(r.price)}</td></tr></table>`; html+='</body></html>'; const w=window.open('','_blank'); if(w){w.document.write(html);w.document.close();w.print();} }

function Analytics(){
 const [d,setD]=useState<any>(null); useEffect(()=>{api('/analytics').then(setD)},[]); if(!d) return <div className="card">Učitavanje analitike...</div>;
 const chart=(rows:any[], key:string, label:string)=><div className="card"><h3>{label}</h3>{rows?.length?rows.map((r:any,i:number)=><div className="bar" key={i}><span>{r.m?date(r.m):(r.plate||r.name||r.status||('Modul '+r.module_id))}</span><b>{money(r[key]||r.total||r.amount||0)}</b></div>):<p className="muted">Nema podataka.</p>}</div>;
 return <div className="grid two">{chart(d.monthlyRevenue,'revenue','Prihod po mjesecima')}{chart(d.monthlyExpenses,'expenses','Troškovi po mjesecima')}{chart(d.fuelByTruck,'total','Gorivo po kamionu')}{chart(d.driverPerformance,'revenue','Učinak vozača')}{chart(d.invoiceStatus,'total','Status faktura')}{chart(d.featureReports,'amount','Izvještaji 150 funkcija')}</div>
}
function Backup({setToast}:any){ const [data,setData]=useState<any>(null); async function run(){try{const d=await api('/backup',{method:'POST'}); setData(d); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'})); a.download='adriatms-backup.json'; a.click(); setToast('Backup kreiran i preuzet.')}catch(e:any){setToast(e.message)}} return <div className="card"><h3>Backup / export</h3><p>Izvoz svih podataka tvrtke iz Neon baze u JSON datoteku. Ne koristi vanjske servise.</p><button onClick={run}>Kreiraj backup sada</button>{data&&<pre className="code">{JSON.stringify({exportedAt:data.exportedAt, tables:Object.fromEntries(Object.entries(data.tables).map(([k,v]:any)=>[k,v.length]))},null,2)}</pre>}</div> }
function Admin({setToast}:any){ const [rows,setRows]=useState<Row[]>([]),[edit,setEdit]=useState<Row|null>(null); async function load(){setRows(await api('/admin/users'))} useEffect(()=>{load().catch((e:any)=>setToast(e.message))},[]); async function save(u:Row){try{await api('/admin/users'+(u.id?'/'+u.id:''),{method:u.id?'PUT':'POST',body:JSON.stringify(u)});setEdit(null);await load();setToast('Korisnik spremljen.')}catch(e:any){setToast(e.message)}} return <><div className="toolbar"><button onClick={()=>setEdit({role:'viewer',active:true})}>+ Novi korisnik</button></div><div className="card tableWrap"><table><thead><tr><th>Ime</th><th>Email</th><th>Rola</th><th>Aktivan</th><th>Akcije</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.email}</td><td>{r.role}</td><td>{r.active?'Da':'Ne'}</td><td><button onClick={()=>setEdit(r)}>Uredi</button></td></tr>)}</tbody></table></div>{edit&&<SimpleUserForm row={edit} onClose={()=>setEdit(null)} onSave={save}/>}</> }
function SimpleUserForm({row,onClose,onSave}:any){ const [f,setF]=useState<Row>(row); return <div className="modal"><form className="modalCard" onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="modalHead"><h2>Korisnik</h2><button type="button" onClick={onClose}>✕</button></div><div className="formGrid"><label>Ime<input required value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Email<input required type="email" value={f.email||''} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Rola<select value={f.role||'viewer'} onChange={e=>setF({...f,role:e.target.value})}>{['admin','dispatcher','accountant','driver','viewer'].map(x=><option key={x}>{x}</option>)}</select></label><label>Nova lozinka<input type="password" onChange={e=>setF({...f,password:e.target.value})}/></label><label>Aktivan<input type="checkbox" checked={f.active!==false} onChange={e=>setF({...f,active:e.target.checked})}/></label></div><div className="modalActions"><button type="button" onClick={onClose}>Odustani</button><button>Spremi</button></div></form></div> }
function PdfCenter(){ return <div className="card"><h3>PDF centar</h3><p>PDF se generira kroz browser print mehanizam bez vanjskih SaaS servisa. Otvorite Fakture, Ponude, Putne naloge ili CMR i kliknite PDF/Ispis.</p><ul><li>Račun kupcu s PDV obračunom</li><li>Ponuda kupcu</li><li>Putni nalog vozaču</li><li>CMR / transportni dokument</li></ul><button onClick={()=>window.print()}>Ispiši trenutni ekran</button></div> }
function ExcelCenter(){ return <div className="card"><h3>Excel centar</h3><p>Svaki modul ima CSV/Excel gumb. Izvoz je lokalni CSV kompatibilan s Excelom, bez vanjskih servisa.</p><p>Podržano za flotu, vozače, kupce, prijevoze, fakture, gorivo, servise, GPS, tahograf, plaće, CMR i 150 poslovnih funkcija.</p></div> }
function Features150({setToast}:any){ const [mods,setMods]=useState<Row[]>([]),[mid,setMid]=useState(1),[rows,setRows]=useState<Row[]>([]),[edit,setEdit]=useState<Row|null>(null); useEffect(()=>{api('/feature-modules').then(setMods)},[]); async function load(id=mid){setRows(await api('/feature-records/'+id))} useEffect(()=>{load().catch((e:any)=>setToast(e.message))},[mid]); const mod=mods.find(m=>m.id===mid); async function save(r:Row){try{const payload={title:r.title,status:r.status,priority:r.priority,amount:r.amount,due_date:r.due_date,data:{opis:r.opis,odgovorna_osoba:r.odgovorna_osoba,rizik:r.rizik,napomena:r.napomena}}; await api('/feature-records/'+(r.id?r.id:mid),{method:r.id?'PUT':'POST',body:JSON.stringify(payload)});setEdit(null);await load();setToast('Funkcijski zapis spremljen.')}catch(e:any){setToast(e.message)}} async function del(id:string){if(confirm('Obrisati zapis?')){await api('/feature-records/'+id,{method:'DELETE'});await load();}}
 return <><div className="toolbar"><select value={mid} onChange={e=>setMid(Number(e.target.value))}>{mods.map(m=><option key={m.id} value={m.id}>{m.id}. {m.name} — {m.category}</option>)}</select><button onClick={()=>setEdit({status:'open',priority:'normal'})}>+ Novi zapis</button></div><div className="card"><h3>{mod?.name}</h3><p>{mod?.description}</p><div className="kpis small"><K label="Kategorija" val={mod?.category}/><K label="Zapisa" val={rows.length}/><K label="Otvoreno" val={rows.filter(r=>r.status!=='closed').length}/><K label="Vrijednost" val={money(rows.reduce((s,r)=>s+Number(r.amount||0),0))}/></div></div><div className="card tableWrap"><table><thead><tr><th>Naslov</th><th>Status</th><th>Prioritet</th><th>Iznos</th><th>Rok</th><th>Akcije</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.status}</td><td>{r.priority}</td><td>{money(r.amount)}</td><td>{date(r.due_date)}</td><td><button onClick={()=>setEdit({...r,...(r.data||{})})}>Uredi</button><button className="danger" onClick={()=>del(r.id)}>Briši</button></td></tr>)}</tbody></table></div>{edit&&<FeatureForm row={edit} onClose={()=>setEdit(null)} onSave={save}/>}</> }
function FeatureForm({row,onClose,onSave}:any){ const [f,setF]=useState<Row>(row); return <div className="modal"><form className="modalCard" onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="modalHead"><h2>Poslovna funkcija</h2><button type="button" onClick={onClose}>✕</button></div><div className="formGrid"><label>Naslov<input required value={f.title||''} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Status<select value={f.status||'open'} onChange={e=>setF({...f,status:e.target.value})}>{['open','in_progress','waiting','closed'].map(x=><option key={x}>{x}</option>)}</select></label><label>Prioritet<select value={f.priority||'normal'} onChange={e=>setF({...f,priority:e.target.value})}>{['low','normal','high','critical'].map(x=><option key={x}>{x}</option>)}</select></label><label>Iznos<input type="number" value={f.amount||0} onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Rok<input type="date" value={f.due_date||''} onChange={e=>setF({...f,due_date:e.target.value})}/></label><label>Rizik<select value={f.rizik||'srednji'} onChange={e=>setF({...f,rizik:e.target.value})}>{['nizak','srednji','visok'].map(x=><option key={x}>{x}</option>)}</select></label><label>Opis<textarea required value={f.opis||''} onChange={e=>setF({...f,opis:e.target.value})}/></label><label>Odgovorna osoba<input value={f.odgovorna_osoba||''} onChange={e=>setF({...f,odgovorna_osoba:e.target.value})}/></label><label>Napomena<textarea value={f.napomena||''} onChange={e=>setF({...f,napomena:e.target.value})}/></label></div><div className="modalActions"><button type="button" onClick={onClose}>Odustani</button><button>Spremi</button></div></form></div> }

createRoot(document.getElementById('root')!).render(<App/>);
