import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type Row = Record<string, any>;
type Field = { key:string; label:string; type?:'text'|'number'|'date'|'select'|'textarea'|'checkbox'; required?:boolean; options?:string[]; ref?:string; step?:string };
type Module = { key:string; label:string; icon:string; desc:string; fields:Field[]; print?:'invoice'|'transport'|'offer' };
const money = (n:any) => new Intl.NumberFormat('hr-HR',{style:'currency',currency:'EUR'}).format(Number(n||0));
const date = (d:any) => d ? new Date(d).toLocaleDateString('hr-HR') : '—';
const tokenKey='adriatms_token';
const googleMapsKey = (import.meta as any).env?.VITE_GOOGLE_MAPS_API_KEY || '';
declare global { interface Window { google?: any; __gmapsPromise?: Promise<void>; } }
function loadGoogleMaps(){
  if(!googleMapsKey) return Promise.reject(new Error('Nedostaje VITE_GOOGLE_MAPS_API_KEY'));
  if(window.google?.maps) return Promise.resolve();
  if(window.__gmapsPromise) return window.__gmapsPromise;
  window.__gmapsPromise = new Promise((resolve,reject)=>{
    const script=document.createElement('script');
    script.src=`https://maps.googleapis.com/maps/api/js?key=${encodeURIComponent(googleMapsKey)}&libraries=places`;
    script.async=true; script.defer=true; script.onload=()=>resolve(); script.onerror=()=>reject(new Error('Google Maps se nije učitao. Provjeri API key i billing.'));
    document.head.appendChild(script);
  });
  return window.__gmapsPromise;
}
async function api(path:string, opts:any={}){
  const token = localStorage.getItem(tokenKey);
  const res = await fetch('/api'+path, { ...opts, headers:{ 'Content-Type':'application/json', ...(token?{Authorization:'Bearer '+token}:{}), ...(opts.headers||{}) }});
  const data = await res.json().catch(()=>({})); if(!res.ok) throw new Error(data.error || 'API greška'); return data;
}

const modules:Module[] = [
 {key:'trucks',label:'Kamioni',icon:'truck',desc:'Vozni park, registracije, potrošnja i statusi.',fields:[{key:'plate',label:'Registracija',required:true},{key:'brand',label:'Marka'},{key:'model',label:'Model'},{key:'year',label:'Godina',type:'number'},{key:'vin',label:'VIN'},{key:'euro_class',label:'EURO klasa',type:'select',options:['EURO 5','EURO 6','EURO 7']},{key:'fuel_type',label:'Gorivo',type:'select',options:['Diesel','LNG','CNG','Električni']},{key:'avg_consumption',label:'Prosj. l/100km',type:'number',step:'0.1'},{key:'tank_liters',label:'Spremnik L',type:'number'},{key:'odometer_km',label:'Kilometri',type:'number'},{key:'status',label:'Status',type:'select',options:['active','service','inactive']},{key:'registration_until',label:'Registracija do',type:'date'},{key:'insurance_until',label:'Osiguranje do',type:'date'}]},
 {key:'drivers',label:'Vozači',icon:'driver',desc:'Vozači, dozvole, tahograf kartice i liječnički.',fields:[{key:'name',label:'Ime i prezime',required:true},{key:'phone',label:'Telefon'},{key:'email',label:'Email'},{key:'license_no',label:'Broj dozvole'},{key:'license_until',label:'Dozvola do',type:'date'},{key:'card_no',label:'Tahograf kartica'},{key:'card_until',label:'Kartica do',type:'date'},{key:'adr_until',label:'ADR do',type:'date'},{key:'medical_until',label:'Liječnički do',type:'date'},{key:'base_salary',label:'Osnovica plaće',type:'number'},{key:'status',label:'Status',type:'select',options:['active','vacation','inactive']} ]},
 {key:'trailers',label:'Prikolice',icon:'trailer',desc:'Poluprikolice, nosivost, volumen i registracija.',fields:[{key:'plate',label:'Registracija',required:true},{key:'type',label:'Tip',type:'select',options:['cerada','hladnjača','cisterna','kiper','platforma']},{key:'capacity_kg',label:'Nosivost kg',type:'number'},{key:'volume_m3',label:'Volumen m³',type:'number'},{key:'registration_until',label:'Registracija do',type:'date'},{key:'status',label:'Status',type:'select',options:['active','service','inactive']} ]},
 {key:'customers',label:'Kupci',icon:'customers',desc:'CRM kupaca, uvjeti plaćanja i podaci za račune.',fields:[{key:'name',label:'Naziv',required:true},{key:'oib',label:'OIB'},{key:'vat_id',label:'VAT ID'},{key:'email',label:'Email'},{key:'phone',label:'Telefon'},{key:'address',label:'Adresa'},{key:'city',label:'Grad'},{key:'country',label:'Država'},{key:'payment_days',label:'Valuta plaćanja dana',type:'number'}]},
 {key:'suppliers',label:'Dobavljači',icon:'suppliers',desc:'Dobavljači goriva, servisa, dijelova i podizvođača.',fields:[{key:'name',label:'Naziv',required:true},{key:'oib',label:'OIB'},{key:'email',label:'Email'},{key:'phone',label:'Telefon'},{key:'address',label:'Adresa'},{key:'city',label:'Grad'},{key:'country',label:'Država'},{key:'category',label:'Kategorija',type:'select',options:['gorivo','servis','gume','cestarina','podizvođač','ostalo']},{key:'payment_days',label:'Valuta plaćanja',type:'number'}]},
 {key:'routes',label:'Rute',icon:'routes',desc:'Izračun udaljenosti, goriva, zakonskih pauza i mjesta odmora.',fields:[{key:'name',label:'Naziv',required:true},{key:'origin',label:'Polazište',required:true},{key:'destination',label:'Odredište',required:true},{key:'via',label:'Preko / via'},{key:'distance_km',label:'Udaljenost km',type:'number'},{key:'duration_h',label:'Trajanje h',type:'number'},{key:'fuel_liters',label:'Gorivo L',type:'number'},{key:'toll_estimate',label:'Cestarina procjena',type:'number'}]},
 {key:'transports',label:'Dispečing / prijevozi',icon:'dispatch',desc:'Planiranje prijevoza, tereti, vozila, vozači i putni nalog.',print:'transport',fields:[{key:'order_no',label:'Putni nalog',required:true},{key:'customer_id',label:'Kupac',ref:'customers'},{key:'truck_id',label:'Kamion',ref:'trucks'},{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'trailer_id',label:'Prikolica',ref:'trailers'},{key:'route_id',label:'Ruta',ref:'routes'},{key:'status',label:'Status',type:'select',options:['planned','loading','in_transit','delivered','invoiced','cancelled']},{key:'load_date',label:'Datum utovara',type:'date'},{key:'unload_date',label:'Datum istovara',type:'date'},{key:'loading_place',label:'Mjesto utovara'},{key:'unloading_place',label:'Mjesto istovara'},{key:'cargo_desc',label:'Teret',type:'textarea'},{key:'cargo_weight_kg',label:'Težina kg',type:'number'},{key:'price',label:'Cijena',type:'number'},{key:'currency',label:'Valuta',type:'select',options:['EUR','HRK','USD']},{key:'notes',label:'Napomene',type:'textarea'}]},
 {key:'expenses',label:'Troškovi vozača',icon:'expenses',desc:'Dnevnice, parking, cestarine, ostali troškovi.',fields:[{key:'transport_id',label:'Prijevoz',ref:'transports'},{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'supplier_id',label:'Dobavljač',ref:'suppliers'},{key:'type',label:'Tip',type:'select',options:['dnevnica','parking','cestarina','pranje','popravak','ostalo'],required:true},{key:'amount',label:'Iznos',type:'number',required:true},{key:'currency',label:'Valuta',type:'select',options:['EUR','HRK','USD']},{key:'expense_date',label:'Datum',type:'date'},{key:'description',label:'Opis',type:'textarea'},{key:'paid',label:'Plaćeno',type:'checkbox'}]},
 {key:'fuel_entries',label:'Gorivo',icon:'fuel',desc:'Tankiranja, cijena po litri i potrošnja.',fields:[{key:'truck_id',label:'Kamion',ref:'trucks'},{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'entry_date',label:'Datum',type:'date'},{key:'liters',label:'Litara',type:'number',required:true},{key:'price_per_liter',label:'Cijena/L',type:'number',step:'0.001',required:true},{key:'odometer_km',label:'Kilometri',type:'number'},{key:'station',label:'Postaja'},{key:'country',label:'Država'}]},
 {key:'service_records',label:'Servisi',icon:'service',desc:'Servisi, gume, preventivno održavanje i rokovi.',fields:[{key:'truck_id',label:'Kamion',ref:'trucks'},{key:'service_date',label:'Datum',type:'date'},{key:'type',label:'Tip'},{key:'odometer_km',label:'Kilometri',type:'number'},{key:'amount',label:'Iznos',type:'number'},{key:'supplier_id',label:'Dobavljač',ref:'suppliers'},{key:'description',label:'Opis',type:'textarea'},{key:'next_service_date',label:'Sljedeći datum',type:'date'},{key:'next_service_km',label:'Sljedeći km',type:'number'}]},
 {key:'gps_positions',label:'GPS live',icon:'gps',desc:'Live pozicije vozila, brzina, smjer i Google Maps karta flote.',fields:[{key:'truck_id',label:'Kamion',ref:'trucks'},{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'position_time',label:'Vrijeme pozicije',type:'date'},{key:'lat',label:'Latitude',type:'number',required:true,step:'0.000001'},{key:'lng',label:'Longitude',type:'number',required:true,step:'0.000001'},{key:'speed_kmh',label:'Brzina km/h',type:'number'},{key:'heading',label:'Smjer °',type:'number'},{key:'ignition',label:'Kontakt uključen',type:'checkbox'},{key:'source',label:'Izvor',type:'select',options:['manual','mobile','tracker','import']},{key:'note',label:'Napomena',type:'textarea'}]},
 {key:'tachograph_entries',label:'Tahograf',icon:'tachograph',desc:'Radna vremena, vožnja, odmori i automatska upozorenja na EU/RH pravila.',fields:[{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'truck_id',label:'Kamion',ref:'trucks'},{key:'entry_date',label:'Datum',type:'date',required:true},{key:'drive_minutes',label:'Vožnja min',type:'number'},{key:'work_minutes',label:'Rad min',type:'number'},{key:'rest_minutes',label:'Odmor min',type:'number'},{key:'availability_minutes',label:'Raspoloživost min',type:'number'},{key:'note',label:'Napomena',type:'textarea'}]},
 {key:'payrolls',label:'Plaće',icon:'payroll',desc:'Obračun plaća vozača, dnevnice, bonusi, odbici i status isplate.',fields:[{key:'driver_id',label:'Vozač',ref:'drivers'},{key:'period_month',label:'Period YYYY-MM',required:true},{key:'base_salary',label:'Osnovica',type:'number'},{key:'per_diem',label:'Dnevnice',type:'number'},{key:'bonuses',label:'Bonusi',type:'number'},{key:'deductions',label:'Odbici',type:'number'},{key:'gross_total',label:'Bruto ukupno',type:'number'},{key:'net_total',label:'Neto procjena',type:'number'},{key:'status',label:'Status',type:'select',options:['draft','approved','paid']},{key:'note',label:'Napomena',type:'textarea'}]},
 {key:'cmr_documents',label:'CMR',icon:'cmr',desc:'CMR dokumenti s pošiljateljem, primateljem, teretom i PDF ispisom.',print:'transport',fields:[{key:'transport_id',label:'Prijevoz',ref:'transports'},{key:'cmr_no',label:'CMR broj',required:true},{key:'sender',label:'Pošiljatelj'},{key:'consignee',label:'Primatelj'},{key:'carrier',label:'Prijevoznik'},{key:'pickup_place',label:'Mjesto preuzimanja'},{key:'delivery_place',label:'Mjesto isporuke'},{key:'goods_desc',label:'Opis robe',type:'textarea'},{key:'packages',label:'Pakiranja'},{key:'gross_weight_kg',label:'Bruto kg',type:'number'},{key:'instructions',label:'Upute',type:'textarea'},{key:'status',label:'Status',type:'select',options:['draft','issued','signed','archived']} ]},

 {key:'invoices',label:'Fakture',icon:'invoices',desc:'Računi kupcima, PDV, status naplate i PDF ispis.',print:'invoice',fields:[{key:'invoice_no',label:'Broj računa',required:true},{key:'customer_id',label:'Kupac',ref:'customers'},{key:'transport_id',label:'Prijevoz',ref:'transports'},{key:'issue_date',label:'Datum izdavanja',type:'date'},{key:'due_date',label:'Dospijeće',type:'date'},{key:'status',label:'Status',type:'select',options:['draft','sent','paid','overdue','cancelled']},{key:'subtotal',label:'Osnovica',type:'number'},{key:'vat_rate',label:'PDV %',type:'number'},{key:'vat_amount',label:'PDV iznos',type:'number'},{key:'total',label:'Ukupno',type:'number'},{key:'currency',label:'Valuta',type:'select',options:['EUR','HRK','USD']},{key:'notes',label:'Napomene',type:'textarea'}]},
 {key:'offers',label:'Ponude',icon:'offers',desc:'Komercijalne ponude i pretvaranje u prijevoz.',print:'offer',fields:[{key:'offer_no',label:'Broj ponude',required:true},{key:'customer_id',label:'Kupac',ref:'customers'},{key:'issue_date',label:'Datum',type:'date'},{key:'valid_until',label:'Vrijedi do',type:'date'},{key:'status',label:'Status',type:'select',options:['draft','sent','accepted','rejected']},{key:'route_desc',label:'Ruta/opis',type:'textarea'},{key:'price',label:'Cijena',type:'number'},{key:'currency',label:'Valuta',type:'select',options:['EUR','HRK','USD']},{key:'notes',label:'Napomene',type:'textarea'}]},
 {key:'documents',label:'Dokumenti / CMR',icon:'documents',desc:'CMR, police, certifikati i datumi isteka.',fields:[{key:'entity',label:'Entitet',type:'select',options:['truck','driver','transport','customer','company']},{key:'entity_id',label:'ID entiteta'},{key:'doc_type',label:'Tip',type:'select',options:['CMR','registracija','polica','licenca','ugovor','ostalo'],required:true},{key:'title',label:'Naziv',required:true},{key:'file_url',label:'URL/datoteka'},{key:'expires_at',label:'Ističe',type:'date'}]},
 {key:'notifications',label:'Notifikacije',icon:'notifications',desc:'Rokovi, upozorenja i operativne obavijesti.',fields:[{key:'title',label:'Naslov',required:true},{key:'body',label:'Poruka',type:'textarea'},{key:'severity',label:'Prioritet',type:'select',options:['info','warning','danger','success']},{key:'read_at',label:'Pročitano',type:'date'}]},
 {key:'app_settings',label:'Postavke',icon:'settings',desc:'Postavke tvrtke, numeracije, PDV-a, dokumenata i operativnih pravila.',fields:[{key:'setting_key',label:'Ključ postavke',required:true},{key:'setting_value',label:'JSON vrijednost',type:'textarea',required:true}]}
];
const specialViews = [{key:'analytics',label:'Analitika',icon:'analytics'},{key:'backup',label:'Backup',icon:'backup'},{key:'admin',label:'Administracija',icon:'admin'},{key:'pdf',label:'PDF centar',icon:'pdf'},{key:'excel',label:'Excel centar',icon:'excel'},{key:'features150',label:'150 funkcija',icon:'features'}];

const cities:Record<string,[number,number]>={Zagreb:[45.815,15.982],Rijeka:[45.327,14.442],Split:[43.508,16.44],Osijek:[45.555,18.695],Zadar:[44.119,15.232],Pula:[44.866,13.849],Dubrovnik:[42.65,18.094],Ljubljana:[46.056,14.505],Maribor:[46.554,15.645],Graz:[47.07,15.439],Vienna:[48.208,16.373],Budapest:[47.497,19.04],Belgrade:[44.812,20.461],Sarajevo:[43.856,18.413],Munich:[48.135,11.582],Milan:[45.464,9.19],Trieste:[45.65,13.77],Venice:[45.44,12.315],Prague:[50.075,14.438],Warsaw:[52.229,21.012],Bratislava:[48.148,17.107],Frankfurt:[50.11,8.682],Hamburg:[53.551,9.993],Rotterdam:[51.924,4.477],Paris:[48.857,2.352]};
const stops=[['Ravna Gora',45.37,14.94],['Zir',44.33,15.68],['Spačva',45.03,18.92],['Plitvice',44.88,15.62],['Lučko',45.75,15.88],['Sežana',45.71,13.87],['Graz West',47.04,15.36],['Nickelsdorf',47.94,17.07],['Letenye',46.43,16.72],['Ljubljana Barje',46.02,14.46],['München Ost',48.13,11.7],['Trieste Fernetti',45.71,13.81],['Beograd Šimanovci',44.87,20.09]];
function hav(a:[number,number],b:[number,number]){const R=6371, dLat=(b[0]-a[0])*Math.PI/180, dLon=(b[1]-a[1])*Math.PI/180; const x=Math.sin(dLat/2)**2+Math.cos(a[0]*Math.PI/180)*Math.cos(b[0]*Math.PI/180)*Math.sin(dLon/2)**2; return 2*R*Math.asin(Math.sqrt(x));}
function routeCalc(origin:string,destination:string,via:string,cons=30){ const pts=[origin, ...(via?via.split(',').map(s=>s.trim()).filter(Boolean):[]), destination].map(x=>cities[x]).filter(Boolean) as [number,number][]; let km=0; for(let i=1;i<pts.length;i++) km += hav(pts[i-1],pts[i])*1.22; const h=km/68; const rests=[]; for(let t=4.5;t<h;t+=5.25) rests.push({atHour:t, breakMin:t+0.75<h?45:0, rule:'EU 561/2006: nakon najviše 4h30 vožnje obvezna pauza 45 min'}); const near=stops.map(s=>({name:s[0] as string, kmFromRoute: pts[0]?Math.min(...pts.map(p=>hav(p,[s[1] as number,s[2] as number]))):999})).sort((a,b)=>a.kmFromRoute-b.kmFromRoute).slice(0,5); return {distance_km:+km.toFixed(1), duration_h:+h.toFixed(2), fuel_liters:+(km*cons/100).toFixed(1), toll_estimate:+(km*0.18).toFixed(2), rest_plan:rests, stops:near}; }
function MiniMap({origin,destination,via}:{origin:string;destination:string;via?:string}){ const names=[origin,...(via?via.split(',').map(x=>x.trim()).filter(Boolean):[]),destination].filter(x=>cities[x]); const pts=names.map(n=>cities[n]); if(pts.length<2) return <div className="mapEmpty">Unesite gradove iz liste: {Object.keys(cities).slice(0,12).join(', ')}...</div>; const lats=pts.map(p=>p[0]), lons=pts.map(p=>p[1]); const minLat=Math.min(...lats), maxLat=Math.max(...lats), minLon=Math.min(...lons), maxLon=Math.max(...lons); const xy=(p:[number,number])=>[40+((p[1]-minLon)/(maxLon-minLon||1))*520,260-(40+((p[0]-minLat)/(maxLat-minLat||1))*180)]; const line=pts.map(p=>xy(p).join(',')).join(' '); return <svg className="map" viewBox="0 0 600 300"><defs><linearGradient id="g" x1="0" x2="1"><stop stopColor="#0ea5e9"/><stop offset="1" stopColor="#22c55e"/></linearGradient></defs><rect width="600" height="300" rx="20" fill="var(--map)"/><polyline points={line} fill="none" stroke="url(#g)" strokeWidth="6" strokeLinecap="round" strokeLinejoin="round"/>{pts.map((p,i)=>{const [x,y]=xy(p);return <g key={i}><circle cx={x} cy={y} r="9" fill={i===0?'#22c55e':i===pts.length-1?'#ef4444':'#f59e0b'}/><text x={x+12} y={y-10} fill="currentColor" fontSize="13">{names[i]}</text></g>})}</svg> }

function GoogleRouteMap({origin,destination,via,cons,onCalc}:{origin:string;destination:string;via?:string;cons:number;onCalc:(r:any)=>void}){
 const divRef = React.useRef<HTMLDivElement|null>(null); const [err,setErr]=useState('');
 useEffect(()=>{ let alive=true; if(!googleMapsKey){setErr('Google Maps API key nije postavljen. Koristi se fallback karta.'); return;} loadGoogleMaps().then(()=>{ if(!alive||!divRef.current) return; const google=window.google; const map=new google.maps.Map(divRef.current,{center:{lat:45.815,lng:15.982},zoom:6,mapTypeControl:false,streetViewControl:false,fullscreenControl:true}); const renderer=new google.maps.DirectionsRenderer({map,suppressMarkers:false,polylineOptions:{strokeColor:'#0ea5e9',strokeWeight:6}}); const service=new google.maps.DirectionsService(); const waypoints=(via||'').split(',').map(x=>x.trim()).filter(Boolean).map(location=>({location,stopover:false})); service.route({origin,destination,waypoints,travelMode:google.maps.TravelMode.DRIVING,drivingOptions:{departureTime:new Date(),trafficModel:google.maps.TrafficModel.BEST_GUESS},provideRouteAlternatives:false},(result:any,status:string)=>{ if(!alive) return; if(status!=='OK'||!result){setErr('Google Directions greška: '+status); return;} renderer.setDirections(result); const route=result.routes[0]; const legs=route.legs||[]; const meters=legs.reduce((sum:number,l:any)=>sum+(l.distance?.value||0),0); const seconds=legs.reduce((sum:number,l:any)=>sum+(l.duration_in_traffic?.value||l.duration?.value||0),0); const km=meters/1000; const h=seconds/3600; const rest_plan=[]; for(let t=4.5;t<h;t+=5.25) rest_plan.push({atHour:+t.toFixed(2),breakMin:t+0.75<h?45:0,rule:'EU 561/2006: nakon najviše 4h30 vožnje obvezna pauza 45 min'}); const near=stops.map(st=>({name:st[0] as string, kmFromRoute:0})).slice(0,5); onCalc({distance_km:+km.toFixed(1),duration_h:+h.toFixed(2),fuel_liters:+(km*Number(cons||30)/100).toFixed(1),toll_estimate:+(km*0.18).toFixed(2),rest_plan,stops:near,source:'google'}); }); }).catch((e:any)=>setErr(e.message)); return()=>{alive=false}; },[origin,destination,via,cons]);
 return <><div ref={divRef} className="googleMap"></div>{err&&<div className="mapNotice">{err}</div>}</>
}
function truckMarkerSvg(color:string){
 const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="46" height="46" viewBox="0 0 46 46"><filter id="s" x="-20%" y="-20%" width="140%" height="140%"><feDropShadow dx="0" dy="6" stdDeviation="4" flood-color="#0f172a" flood-opacity=".28"/></filter><circle cx="23" cy="23" r="18" fill="${color}" filter="url(#s)"/><path d="M13 18h14v8h2.5l2-3h3.5l2 3v4h-3a3 3 0 0 1-6 0h-9a3 3 0 0 1-6 0h-2v-4h2v-8Zm5 13a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Zm13 0a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3Z" fill="white"/></svg>`;
 return 'data:image/svg+xml;charset=UTF-8,'+encodeURIComponent(svg);
}
function GPSFleetMap({rows,refs}:{rows:Row[];refs:Record<string,Row[]>}){
 const divRef=React.useRef<HTMLDivElement|null>(null); const mapRef=React.useRef<any>(null); const markersRef=React.useRef<any[]>([]); const [err,setErr]=useState(''); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Row|null>(null);
 const filtered=rows.filter(r=>nameOf('trucks',r.truck_id,refs).toLowerCase().includes(query.toLowerCase()) || nameOf('drivers',r.driver_id,refs).toLowerCase().includes(query.toLowerCase()) || String(r.note||'').toLowerCase().includes(query.toLowerCase()));
 useEffect(()=>{ if(!filtered.length) return; if(!googleMapsKey){setErr('Za custom live GPS kartu postavite VITE_GOOGLE_MAPS_API_KEY.'); return;} loadGoogleMaps().then(()=>{ if(!divRef.current) return; const google=window.google; const first=filtered.find(r=>r.lat&&r.lng)||filtered[0]; if(!mapRef.current){ mapRef.current=new google.maps.Map(divRef.current,{center:{lat:Number(first.lat||45.815),lng:Number(first.lng||15.982)},zoom:7,mapTypeControl:false,streetViewControl:false,fullscreenControl:false,zoomControl:true,styles:[{featureType:'poi',stylers:[{visibility:'off'}]},{featureType:'transit',stylers:[{visibility:'off'}]},{featureType:'road',elementType:'geometry',stylers:[{color:'#e5eef8'}]},{featureType:'water',stylers:[{color:'#bfdbfe'}]}]}); }
 markersRef.current.forEach(m=>m.setMap(null)); markersRef.current=[]; const bounds=new google.maps.LatLngBounds(); filtered.filter(r=>r.lat&&r.lng).forEach(r=>{ const pos={lat:Number(r.lat),lng:Number(r.lng)}; bounds.extend(pos); const status=Number(r.speed_kmh||0)>3?'#16a34a':'#f59e0b'; const marker=new google.maps.Marker({map:mapRef.current,position:pos,title:`${nameOf('trucks',r.truck_id,refs)} · ${r.speed_kmh||0} km/h`,icon:{url:truckMarkerSvg(status),scaledSize:new google.maps.Size(46,46)}}); marker.addListener('click',()=>setSelected(r)); markersRef.current.push(marker); }); if(filtered.length>1) mapRef.current.fitBounds(bounds); else mapRef.current.setCenter({lat:Number(first.lat||45.815),lng:Number(first.lng||15.982)}); }).catch((e:any)=>setErr(e.message)); },[filtered.length,query,refs]);
 return <div className="fleetConsole"><aside className="fleetPanel"><div className="fleetHead"><Icon name="gps"/><div><h3>Live flota</h3><p>Custom GPS kontrolni centar</p></div></div><input className="fleetSearch" placeholder="Traži kamion, vozača ili napomenu" value={query} onChange={e=>setQuery(e.target.value)}/><div className="fleetList">{filtered.map(r=><button key={r.id} className={selected?.id===r.id?'active':''} onClick={()=>setSelected(r)}><b>{nameOf('trucks',r.truck_id,refs)}</b><span>{nameOf('drivers',r.driver_id,refs)} · {r.speed_kmh||0} km/h</span><small>{Number(r.lat).toFixed?.(4)}, {Number(r.lng).toFixed?.(4)}</small></button>)}</div></aside><section className="fleetMapWrap"><div ref={divRef} className="googleMap fleetPro"></div>{err&&<div className="mapNotice">{err}</div>}{!rows.length&&<p className="muted emptyFleet">Nema GPS pozicija. Dodajte vozilo s lat/lng koordinatama.</p>}{selected&&<div className="vehicleCard"><div><b>{nameOf('trucks',selected.truck_id,refs)}</b><span>{nameOf('drivers',selected.driver_id,refs)}</span></div><div className="vehicleStats"><span>{selected.speed_kmh||0} km/h</span><span>{selected.ignition?'Kontakt ON':'Kontakt OFF'}</span><span>{date(selected.position_time)}</span></div><p>{selected.note||'Nema napomene.'}</p></div>}</section></div>
}

function nameOf(ref:string|undefined,id:any,refs:Record<string,Row[]>){ if(!ref||!id) return '—'; const r=refs[ref]?.find(x=>x.id===id); return r?.name || r?.plate || r?.order_no || r?.invoice_no || r?.offer_no || id?.slice?.(0,8) || '—'; }


function Icon({name}:{name:string}){
 const paths:Record<string,string>={
  dashboard:'M3 13h8V3H3v10Zm0 8h8v-6H3v6Zm10 0h8V11h-8v10Zm0-18v6h8V3h-8Z',
  truck:'M3 6h11v8h2.2l1.8-3h3l2 3v4h-2a3 3 0 0 1-6 0h-5a3 3 0 0 1-6 0H3V6Zm3 12a1 1 0 1 0 2 0 1 1 0 0 0-2 0Zm12 0a1 1 0 1 0 2 0 1 1 0 0 0-2 0Z',
  driver:'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm-7 9a7 7 0 0 1 14 0H5Z',
  trailer:'M4 7h12v9h2V9h3v7h1v3h-2a2 2 0 0 1-4 0H9a2 2 0 0 1-4 0H3v-3h1V7Z',
  customers:'M4 5h16v16H4V5Zm3 4h4V7H7v2Zm0 4h10v-2H7v2Zm0 4h10v-2H7v2Z',
  suppliers:'M3 21V9l6 3V9l6 3V5h6v16H3Zm14-2h2v-2h-2v2Zm-6 0h2v-2h-2v2Zm-6 0h2v-2H5v2Z',
  routes:'M6 18a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm12-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM8.5 15H15a3 3 0 0 0 0-6H9',
  dispatch:'M4 6h16v12H4V6Zm3 3v2h10V9H7Zm0 4v2h7v-2H7Z',
  expenses:'M3 6h18v12H3V6Zm3 3a3 3 0 0 1-3 3v0a3 3 0 0 1 3 3h12a3 3 0 0 1 3-3 3 3 0 0 1-3-3H6Zm6 5a2 2 0 1 0 0-4 2 2 0 0 0 0 4Z',
  fuel:'M6 3h9v18H6V3Zm2 2v5h5V5H8Zm9 1 3 3v9a2 2 0 0 1-4 0v-5h-1v-2h3V9l-2-2 1-1Z',
  service:'M22 19.6 19.6 22l-6.3-6.3a7 7 0 0 1-8.9-8.9l4.2 4.2 2.8-2.8L7.2 4a7 7 0 0 1 8.9 8.9L22 19.6Z',
  gps:'M12 2a7 7 0 0 0-7 7c0 5.2 7 13 7 13s7-7.8 7-13a7 7 0 0 0-7-7Zm0 9.5A2.5 2.5 0 1 1 12 6a2.5 2.5 0 0 1 0 5.5Z',
  tachograph:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm1 5v5l4 2-1 1.7-5-3V7h2Z',
  payroll:'M4 5h16v14H4V5Zm3 3v2h10V8H7Zm0 4v2h6v-2H7Zm9 0v4h2v-4h-2Z',
  cmr:'M6 2h9l3 3v17H6V2Zm8 1v4h4M8 11h8M8 15h8M8 19h5',
  invoices:'M7 2h10v20l-2-1-2 1-2-1-2 1-2-1V2Zm3 6h4M10 12h4M10 16h3',
  offers:'M5 3h14v18H5V3Zm3 4h8M8 11h8M8 15h5',
  documents:'M4 4h7l2 2h7v14H4V4Z',
  notifications:'M12 22a2.5 2.5 0 0 0 2.4-2h-4.8A2.5 2.5 0 0 0 12 22Zm7-5H5l2-2V9a5 5 0 0 1 10 0v6l2 2Z',
  settings:'M19.4 13.5a7.8 7.8 0 0 0 0-3l2-1.5-2-3.5-2.4 1a8 8 0 0 0-2.6-1.5L14 2h-4l-.4 3a8 8 0 0 0-2.6 1.5l-2.4-1-2 3.5 2 1.5a7.8 7.8 0 0 0 0 3l-2 1.5 2 3.5 2.4-1a8 8 0 0 0 2.6 1.5l.4 3h4l.4-3a8 8 0 0 0 2.6-1.5l2.4 1 2-3.5-2-1.5ZM12 15a3 3 0 1 1 0-6 3 3 0 0 1 0 6Z',
  analytics:'M4 19h16v2H4V3h2v16Zm4-2V9h3v8H8Zm5 0V5h3v12h-3Zm5 0v-6h3v6h-3Z',
  backup:'M12 3a9 9 0 0 1 8.9 8h-3a6 6 0 1 0-1.8 4.3L14 13h7v7l-2.7-2.7A9 9 0 1 1 12 3Z',
  admin:'M16 11a4 4 0 1 0-8 0 4 4 0 0 0 8 0ZM4 21a8 8 0 0 1 16 0H4Z',
  pdf:'M6 2h9l5 5v15H6V2Zm8 1v5h5M8 14h8M8 18h5',
  excel:'M4 4h16v16H4V4Zm3 3 3 5-3 5h3l1.5-2.8L13 17h3l-3-5 3-5h-3l-1.5 2.8L10 7H7Z',
  features:'M4 4h7v7H4V4Zm9 0h7v7h-7V4ZM4 13h7v7H4v-7Zm9 0h7v7h-7v-7Z'
 };
 return <svg className="ico" viewBox="0 0 24 24" aria-hidden="true"><path d={paths[name]||paths.features}/></svg>
}

function App(){
 const [token,setToken]=useState(localStorage.getItem(tokenKey)); const [user,setUser]=useState<any>(null); const [company,setCompany]=useState<any>(null); const [view,setView]=useState('dashboard'); const [theme,setTheme]=useState(localStorage.getItem('theme')||'light'); const [toast,setToast]=useState('');
 useEffect(()=>{document.documentElement.dataset.theme=theme; localStorage.setItem('theme',theme)},[theme]);
 useEffect(()=>{ if(token) api('/me').then(d=>{setUser(d.user);setCompany(d.company)}).catch(()=>logout()); },[token]);
 function logout(){localStorage.removeItem(tokenKey);setToken(null);setUser(null);}
 if(!token) return <Auth onLogin={(t:string,u:any,c:any)=>{localStorage.setItem(tokenKey,t);setToken(t);setUser(u);setCompany(c)}} setToast={setToast} toast={toast}/>;
 const mod=modules.find(m=>m.key===view);
 return <div className="shell"><aside><div className="brand"><b>AdriaTMS</b><span>ERP za prijevoznike</span></div><button className={view==='dashboard'?'sel':''} onClick={()=>setView('dashboard')}><Icon name="dashboard"/> <span>Dashboard</span></button>{modules.map(m=><button key={m.key} className={view===m.key?'sel':''} onClick={()=>setView(m.key)}><Icon name={m.icon}/> <span>{m.label}</span></button>)}{specialViews.map(v=><button key={v.key} className={view===v.key?'sel':''} onClick={()=>setView(v.key)}><Icon name={v.icon}/> <span>{v.label}</span></button>)}<div className="muted block">Svi moduli iz specifikacije su aktivni: Dashboard, flota, GPS, tahograf, financije, PDF/Excel, analitika, backup, postavke, administracija i 150 poslovnih funkcija.</div></aside><main><header><div><h1>{mod?mod.label:'Dashboard'}</h1><p>{mod?mod.desc:'Pregled flote, prihoda, troškova i rokova.'}</p></div><div className="headerActions"><span className="pill">{company?.name}</span><button onClick={()=>setTheme(theme==='dark'?'light':'dark')}>{theme==='dark'?'☀️':'🌙'}</button><button onClick={logout}>Odjava</button></div></header>{toast&&<div className="toast" onClick={()=>setToast('')}>{toast}</div>}{view==='dashboard'?<Dashboard setView={setView}/>:view==='analytics'?<Analytics/>:view==='backup'?<Backup setToast={setToast}/>:view==='admin'?<Admin setToast={setToast}/>:view==='pdf'?<PdfCenter/>:view==='excel'?<ExcelCenter/>:view==='features150'?<Features150 setToast={setToast}/>:mod?<ModuleView module={mod} setToast={setToast}/>:<Dashboard setView={setView}/>}</main></div>
}
function Auth({onLogin,setToast,toast}:any){ const [mode,setMode]=useState<'login'|'register'>('login'); const [f,setF]=useState<any>({country:'HR'}); const [busy,setBusy]=useState(false); async function submit(e:any){ e.preventDefault(); setBusy(true); try{ const d= await api('/auth/'+mode,{method:'POST',body:JSON.stringify(f)}); onLogin(d.token,d.user,d.company);}catch(e:any){setToast(e.message)} finally{setBusy(false)} } async function setup(){ try{setBusy(true); await api('/setup',{method:'POST'}); setToast('Baza je inicijalizirana. Sada se možete registrirati.')}catch(e:any){setToast(e.message)}finally{setBusy(false)} }
 return <div className="auth"><div className="authCard"><h1>AdriaTMS ERP</h1><p>Standalone Netlify + Neon aplikacija za transport, flotu, fakture i operativu.</p>{toast&&<div className="toast">{toast}</div>}<div className="tabs"><button className={mode==='login'?'sel':''} onClick={()=>setMode('login')}>Prijava</button><button className={mode==='register'?'sel':''} onClick={()=>setMode('register')}>Registracija tvrtke</button></div><form onSubmit={submit}>{mode==='register'&&<><input required placeholder="Naziv tvrtke" onChange={e=>setF({...f,companyName:e.target.value})}/><input required placeholder="OIB tvrtke" onChange={e=>setF({...f,oib:e.target.value})}/><input required placeholder="Vaše ime" onChange={e=>setF({...f,name:e.target.value})}/><input placeholder="Adresa" onChange={e=>setF({...f,address:e.target.value})}/><input placeholder="Grad" onChange={e=>setF({...f,city:e.target.value})}/></>} {mode==='login'||mode==='register'?<><input required type="email" placeholder="Email" onChange={e=>setF({...f,email:e.target.value})}/><input required type="password" placeholder="Lozinka" onChange={e=>setF({...f,password:e.target.value})}/></>:null}<button disabled={busy}>{busy?'Radim...':mode==='login'?'Prijavi se':'Registriraj tvrtku'}</button></form><button className="ghost" onClick={setup}>Prvi put? Inicijaliziraj Neon bazu</button><small>Sigurnost: lozinke se spremaju kao bcrypt hash, sesija je JWT, podaci su odvojeni po company_id.</small></div></div> }
function Dashboard({setView}:any){ const [d,setD]=useState<any>(null); useEffect(()=>{api('/dashboard').then(setD)},[]); if(!d) return <div className="grid"><div className="card">Učitavanje...</div></div>; const revenue=(d.transports||[]).reduce((s:any,x:any)=>s+Number(x.total||0),0); const invTotal=(d.invoices||[]).reduce((s:any,x:any)=>s+Number(x.total||0),0); return <><div className="kpis"><K label="Kamioni" val={d.trucks}/><K label="Vozači" val={d.drivers}/><K label="Prihod prijevoza" val={money(revenue)}/><K label="Fakturirano" val={money(invTotal)}/><K label="Gorivo mj." val={money(d.monthlyFuel.total)}/><K label="Troškovi mj." val={money(d.monthlyExpenses+d.monthlyService)}/></div><div className="grid two"><div className="card"><h3>Status prijevoza</h3>{(d.transports||[]).map((x:any)=><div className="row" key={x.status}><b>{x.status}</b><span>{x.n} · {money(x.total)}</span></div>)}<button onClick={()=>setView('transports')}>Otvori dispečing</button></div><div className="card"><h3>Upozorenja rokova</h3>{d.alerts?.length?d.alerts.map((a:any,i:number)=><div className="alert" key={i}>{a.type}: <b>{a.label}</b> do {date(a.due)}</div>):<p className="muted">Nema rokova u sljedećih 30 dana.</p>}</div></div><div className="card"><h3>Što je implementirano</h3><p>CRUD, validacije, role-permissions, audit log, izračun ruta/goriva/pauza, offline karta, preporuke odmorišta, putni nalog, fakture/ponude s ispisom u PDF kroz browser print, CSV/Excel izvoz, dashboard i responsive dark/light UI.</p></div></> }
function K({label,val}:any){return <div className="kpi"><span>{label}</span><b>{val}</b></div>}
function ModuleView({module,setToast}:{module:Module;setToast:(s:string)=>void}){ const [rows,setRows]=useState<Row[]>([]), [refs,setRefs]=useState<Record<string,Row[]>>({}), [edit,setEdit]=useState<Row|null>(null), [search,setSearch]=useState(''); const [route,setRoute]=useState<any>(null); const refNames=Array.from(new Set(module.fields.map(f=>f.ref).filter(Boolean))) as string[]; async function load(){ const [r,...rr]=await Promise.all([api('/'+module.key+'?search='+encodeURIComponent(search)),...refNames.map(x=>api('/'+x))]); setRows(r); const obj:any={}; refNames.forEach((n,i)=>obj[n]=rr[i]); setRefs(obj); }
 useEffect(()=>{load().catch(e=>setToast(e.message))},[module.key]); async function save(data:Row){ try{ if(module.key==='invoices'){data.vat_amount=+(Number(data.subtotal||0)*Number(data.vat_rate||25)/100).toFixed(2); data.total=+(Number(data.subtotal||0)+data.vat_amount).toFixed(2)} if(module.key==='routes'){data.rest_plan=route?.rest_plan||data.rest_plan}
      if(module.key==='app_settings' && typeof data.setting_value==='string'){try{data.setting_value=JSON.parse(data.setting_value)}catch{throw new Error('Postavka mora biti valjani JSON, npr. {"pdv":25}')}} await api('/'+module.key+(data.id?'/'+data.id:''),{method:data.id?'PUT':'POST',body:JSON.stringify(data)}); setEdit(null); await load(); setToast('Spremljeno.')}catch(e:any){setToast(e.message)} }
 async function del(id:string){ if(confirm('Obrisati zapis?')) try{await api('/'+module.key+'/'+id,{method:'DELETE'}); await load(); setToast('Obrisano.')}catch(e:any){setToast(e.message)} }
 async function next(){ const kind=module.key==='invoices'?'invoice':module.key==='offers'?'offer':'transport'; const n=await api('/next-number/'+kind); setEdit({...(edit||{}), [module.key==='invoices'?'invoice_no':module.key==='offers'?'offer_no':'order_no']:n.number}); }
 function exportCsv(){ const csv=[Object.keys(rows[0]||{}).join(';'),...rows.map(r=>Object.values(r).map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';'))].join('\n'); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'})); a.download=module.key+'.csv'; a.click(); }
 return <><div className="toolbar"><input placeholder="Pretraži..." value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load()}}/><button onClick={load}>Traži</button><button onClick={()=>setEdit({})}>+ Novi zapis</button>{['transports','invoices','offers'].includes(module.key)&&<button onClick={next}>Sljedeći broj</button>}<button onClick={exportCsv}>Excel/CSV</button></div>{module.key==='routes'&&<RoutePanel onCalc={setRoute}/>} {module.key==='gps_positions'&&<GPSFleetMap rows={rows} refs={refs}/>}<div className="card tableWrap"><table><thead><tr>{module.fields.slice(0,7).map(f=><th key={f.key}>{f.label}</th>)}<th>Akcije</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}>{module.fields.slice(0,7).map(f=><td key={f.key}>{f.ref?nameOf(f.ref,r[f.key],refs):f.type==='checkbox'?(r[f.key]?'Da':'Ne'):String(r[f.key]??'—')}</td>)}<td><button onClick={()=>setEdit(r)}>Uredi</button>{module.print&&<button onClick={()=>printDoc(module.print!,r,refs)}>PDF</button>}<button className="danger" onClick={()=>del(r.id)}>Briši</button></td></tr>)}</tbody></table>{!rows.length&&<p className="muted center">Nema zapisa.</p>}</div>{edit&&<Form module={module} row={edit} refs={refs} route={route} onClose={()=>setEdit(null)} onSave={save}/>}</> }

type AddressValue = { street:string; number:string; postal:string; city:string; country:string; place?:string };
function fullAddress(a:AddressValue){ return [a.street && `${a.street} ${a.number||''}`.trim(), [a.postal,a.city].filter(Boolean).join(' '), a.country].filter(Boolean).join(', '); }
function AddressBox({title,value,onChange,accent}:{title:string;value:AddressValue;onChange:(v:AddressValue)=>void;accent:string}){
 const [suggestions,setSuggestions]=useState<any[]>([]); const [open,setOpen]=useState(false); const q=fullAddress(value);
 useEffect(()=>{ let alive=true; if(!googleMapsKey || q.length<5){setSuggestions([]); return;} const t=setTimeout(()=>{loadGoogleMaps().then(()=>{const svc=new window.google.maps.places.AutocompleteService(); svc.getPlacePredictions({input:q,componentRestrictions:{country:['hr','si','at','de','it','hu','ba','rs']},types:['address']},(preds:any[])=>{if(alive) setSuggestions(preds||[]);});}).catch(()=>{});},350); return()=>{alive=false;clearTimeout(t)}; },[q]);
 function pick(s:any){ const txt=s.description||''; const parts=txt.split(',').map((x:string)=>x.trim()); onChange({...value, place:txt, street:parts[0]||value.street, city:parts[1]||value.city}); setOpen(false); }
 return <div className="addressBox" style={{'--addr':accent} as any}><div className="addrTitle"><span></span><b>{title}</b></div><div className="addressGrid"><input placeholder="Ulica" value={value.street} onFocus={()=>setOpen(true)} onChange={e=>{onChange({...value,street:e.target.value,place:''});setOpen(true)}}/><input placeholder="Broj" value={value.number} onChange={e=>onChange({...value,number:e.target.value,place:''})}/><input placeholder="Poštanski broj" value={value.postal} onChange={e=>onChange({...value,postal:e.target.value,place:''})}/><input placeholder="Grad" value={value.city} onFocus={()=>setOpen(true)} onChange={e=>{onChange({...value,city:e.target.value,place:''});setOpen(true)}}/><input placeholder="Država" value={value.country} onChange={e=>onChange({...value,country:e.target.value,place:''})}/></div><div className="addrPreview">{value.place || fullAddress(value) || 'Unesite točnu adresu'}</div>{open&&suggestions.length>0&&<div className="suggestions">{suggestions.slice(0,5).map((x:any)=><button type="button" key={x.place_id} onClick={()=>pick(x)}><Icon name="gps"/><span>{x.description}</span></button>)}</div>}</div>
}
function RoutePanel({onCalc}:any){
 const [origin,setOrigin]=useState<AddressValue>({street:'',number:'',postal:'',city:'Zagreb',country:'Hrvatska'});
 const [destination,setDestination]=useState<AddressValue>({street:'',number:'',postal:'',city:'Split',country:'Hrvatska'});
 const [via,setVia]=useState(''); const [cons,setCons]=useState(30);
 const originText=origin.place || fullAddress(origin); const destinationText=destination.place || fullAddress(destination);
 const fallback=useMemo(()=>routeCalc(origin.city||originText,destination.city||destinationText,via,Number(cons||30)),[originText,destinationText,via,cons]);
 const [calc,setCalc]=useState<any>({...fallback,originText,destinationText,viaText:via});
 useEffect(()=>{ if(!googleMapsKey) setCalc({...fallback,originText,destinationText,viaText:via}); },[fallback.distance_km,fallback.duration_h,fallback.fuel_liters,originText,destinationText,via]);
 useEffect(()=>onCalc(calc),[calc.distance_km,calc.duration_h,calc.fuel_liters,calc.originText,calc.destinationText]);
 return <div className="mapExperience"><section className="mapControl"><div className="mapControlHead"><Icon name="routes"/><div><h3>Planiranje rute</h3><p>Točne adrese, prijedlozi i live izračun puta.</p></div></div><AddressBox title="Polazište" value={origin} onChange={setOrigin} accent="#16a34a"/><AddressBox title="Odredište" value={destination} onChange={setDestination} accent="#ef4444"/><label className="controlLabel">Međustajališta / via adrese<input placeholder="Npr. Ljubljana, Graz" value={via} onChange={e=>setVia(e.target.value)}/></label><label className="controlLabel">Potrošnja vozila l/100km<input type="number" value={cons} onChange={e=>setCons(Number(e.target.value||30))}/></label><div className="routeStats"><K label="Udaljenost" val={`${calc.distance_km||0} km`}/><K label="Trajanje" val={`${calc.duration_h||0} h`}/><K label="Gorivo" val={`${calc.fuel_liters||0} L`}/><K label="Cestarina" val={money(calc.toll_estimate)}/></div><div className="routeSection"><h4>Zakonske pauze</h4>{calc.rest_plan?.length?calc.rest_plan.map((x:any,i:number)=><div className="ruleItem" key={i}><b>{x.atHour}h</b><span>Pauza {x.breakMin} min · EU/RH 561/2006</span></div>):<p className="muted">Ruta je dovoljno kratka da nema obvezne pauze.</p>}</div><div className="routeSection"><h4>Predložena odmorišta</h4>{(calc.stops||[]).map((s:any)=><span className="pill" key={s.name}>{s.name}</span>)}</div></section><section className="mapCanvasPro">{googleMapsKey?<GoogleRouteMap origin={originText} destination={destinationText} via={via} cons={Number(cons||30)} onCalc={(r:any)=>setCalc({...r,originText,destinationText,viaText:via})}/>:<MiniMap origin={origin.city||'Zagreb'} destination={destination.city||'Split'} via={via}/>}<div className="mapFloating"><b>{calc.source==='google'?'Google Directions ruta':'Fallback ruta'}</b><span>{originText} → {destinationText}</span></div></section></div>
}
function Form({module,row,refs,route,onClose,onSave}:any){ const [f,setF]=useState<Row>(row); useEffect(()=>{ if(module.key==='routes'&&route) setF((x:Row)=>({...x, origin:x.origin||route.originText, destination:x.destination||route.destinationText, via:x.via||route.viaText, distance_km:route.distance_km,duration_h:route.duration_h,fuel_liters:route.fuel_liters,toll_estimate:route.toll_estimate,rest_plan:route.rest_plan})); },[route]); return <div className="modal"><form className="modalCard" onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="modalHead"><h2>{row.id?'Uredi':'Novi'} · {module.label}</h2><button type="button" onClick={onClose}>✕</button></div><div className="formGrid">{module.fields.map((field:Field)=><label key={field.key}>{field.label}{field.ref?<select value={f[field.key]||''} onChange={e=>setF({...f,[field.key]:e.target.value||null})}><option value="">—</option>{refs[field.ref]?.map((r:Row)=><option key={r.id} value={r.id}>{r.name||r.plate||r.order_no||r.invoice_no}</option>)}</select>:field.type==='textarea'?<textarea required={field.required} value={f[field.key]||''} onChange={e=>setF({...f,[field.key]:e.target.value})}/>:field.type==='select'?<select required={field.required} value={f[field.key]||''} onChange={e=>setF({...f,[field.key]:e.target.value})}><option value="">—</option>{field.options?.map(o=><option key={o}>{o}</option>)}</select>:field.type==='checkbox'?<input type="checkbox" checked={!!f[field.key]} onChange={e=>setF({...f,[field.key]:e.target.checked})}/>:<input required={field.required} type={field.type||'text'} step={field.step||'0.01'} value={f[field.key]??''} onChange={e=>setF({...f,[field.key]:e.target.value})}/>}</label>)}</div><div className="modalActions"><button type="button" onClick={onClose}>Odustani</button><button>Spremi</button></div></form></div> }
function printDoc(kind:string,r:Row,refs:Record<string,Row[]>){ const customer=nameOf('customers',r.customer_id,refs), transport=nameOf('transports',r.transport_id,refs), truck=nameOf('trucks',r.truck_id,refs), driver=nameOf('drivers',r.driver_id,refs); let title=kind==='invoice'?'RAČUN':kind==='offer'?'PONUDA':'PUTNI NALOG'; let html=`<html><head><title>${title}</title><style>body{font-family:Arial;padding:36px;color:#111}h1{color:#0f766e}table{width:100%;border-collapse:collapse;margin-top:20px}td,th{border:1px solid #ddd;padding:10px}.right{text-align:right}.muted{color:#666}</style></head><body><h1>${title}</h1><p class="muted">Generirano iz AdriaTMS ERP</p>`; if(kind==='invoice') html+=`<h2>${r.invoice_no}</h2><p>Kupac: <b>${customer}</b></p><p>Datum: ${date(r.issue_date)} · Dospijeće: ${date(r.due_date)}</p><table><tr><th>Opis</th><th class="right">Osnovica</th><th>PDV</th><th class="right">Ukupno</th></tr><tr><td>Prijevoz ${transport}</td><td class="right">${money(r.subtotal)}</td><td>${r.vat_rate}% (${money(r.vat_amount)})</td><td class="right"><b>${money(r.total)}</b></td></tr></table><p>${r.notes||''}</p>`; else if(kind==='transport') html+=`<h2>${r.order_no}</h2><table><tr><td>Kupac</td><td>${customer}</td></tr><tr><td>Vozilo</td><td>${truck}</td></tr><tr><td>Vozač</td><td>${driver}</td></tr><tr><td>Utovar</td><td>${r.loading_place} · ${date(r.load_date)}</td></tr><tr><td>Istovar</td><td>${r.unloading_place} · ${date(r.unload_date)}</td></tr><tr><td>Teret</td><td>${r.cargo_desc} (${r.cargo_weight_kg||0} kg)</td></tr></table><p>Potpis disponenta: ____________________ Potpis vozača: ____________________</p>`; else html+=`<h2>${r.offer_no}</h2><p>Kupac: ${customer}</p><p>Vrijedi do: ${date(r.valid_until)}</p><table><tr><th>Opis</th><th class="right">Cijena</th></tr><tr><td>${r.route_desc||'Usluga prijevoza'}</td><td class="right">${money(r.price)}</td></tr></table>`; html+='</body></html>'; const w=window.open('','_blank'); if(w){w.document.write(html);w.document.close();w.print();} }

function Analytics(){
 const [d,setD]=useState<any>(null); useEffect(()=>{api('/analytics').then(setD)},[]); if(!d) return <div className="card">Učitavanje analitike...</div>;
 const chart=(rows:any[], key:string, label:string)=><div className="card"><h3>{label}</h3>{rows?.length?rows.map((r:any,i:number)=><div className="bar" key={i}><span>{r.m?date(r.m):(r.plate||r.name||r.status||('Modul '+r.module_id))}</span><b>{money(r[key]||r.total||r.amount||0)}</b></div>):<p className="muted">Nema podataka.</p>}</div>;
 return <div className="grid two">{chart(d.monthlyRevenue,'revenue','Prihod po mjesecima')}{chart(d.monthlyExpenses,'expenses','Troškovi po mjesecima')}{chart(d.fuelByTruck,'total','Gorivo po kamionu')}{chart(d.driverPerformance,'revenue','Učinak vozača')}{chart(d.invoiceStatus,'total','Status faktura')}{chart(d.featureReports,'amount','Izvještaji 150 funkcija')}</div>
}
function Backup({setToast}:any){ const [data,setData]=useState<any>(null); async function run(){try{const d=await api('/backup',{method:'POST'}); setData(d); const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:'application/json'})); a.download='adriatms-backup.json'; a.click(); setToast('Backup kreiran i preuzet.')}catch(e:any){setToast(e.message)}} return <div className="card"><h3>Backup / export</h3><p>Izvoz svih podataka tvrtke iz Neon baze u JSON datoteku.</p><button onClick={run}>Kreiraj backup sada</button>{data&&<pre className="code">{JSON.stringify({exportedAt:data.exportedAt, tables:Object.fromEntries(Object.entries(data.tables).map(([k,v]:any)=>[k,v.length]))},null,2)}</pre>}</div> }
function Admin({setToast}:any){ const [rows,setRows]=useState<Row[]>([]),[edit,setEdit]=useState<Row|null>(null); async function load(){setRows(await api('/admin/users'))} useEffect(()=>{load().catch((e:any)=>setToast(e.message))},[]); async function save(u:Row){try{await api('/admin/users'+(u.id?'/'+u.id:''),{method:u.id?'PUT':'POST',body:JSON.stringify(u)});setEdit(null);await load();setToast('Korisnik spremljen.')}catch(e:any){setToast(e.message)}} return <><div className="toolbar"><button onClick={()=>setEdit({role:'viewer',active:true})}>+ Novi korisnik</button></div><div className="card tableWrap"><table><thead><tr><th>Ime</th><th>Email</th><th>Rola</th><th>Aktivan</th><th>Akcije</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.name}</td><td>{r.email}</td><td>{r.role}</td><td>{r.active?'Da':'Ne'}</td><td><button onClick={()=>setEdit(r)}>Uredi</button></td></tr>)}</tbody></table></div>{edit&&<SimpleUserForm row={edit} onClose={()=>setEdit(null)} onSave={save}/>}</> }
function SimpleUserForm({row,onClose,onSave}:any){ const [f,setF]=useState<Row>(row); return <div className="modal"><form className="modalCard" onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="modalHead"><h2>Korisnik</h2><button type="button" onClick={onClose}>✕</button></div><div className="formGrid"><label>Ime<input required value={f.name||''} onChange={e=>setF({...f,name:e.target.value})}/></label><label>Email<input required type="email" value={f.email||''} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Rola<select value={f.role||'viewer'} onChange={e=>setF({...f,role:e.target.value})}>{['admin','dispatcher','accountant','driver','viewer'].map(x=><option key={x}>{x}</option>)}</select></label><label>Nova lozinka<input type="password" onChange={e=>setF({...f,password:e.target.value})}/></label><label>Aktivan<input type="checkbox" checked={f.active!==false} onChange={e=>setF({...f,active:e.target.checked})}/></label></div><div className="modalActions"><button type="button" onClick={onClose}>Odustani</button><button>Spremi</button></div></form></div> }
function PdfCenter(){ return <div className="card"><h3>PDF centar</h3><p>PDF se generira kroz browser print mehanizam. Otvorite Fakture, Ponude, Putne naloge ili CMR i kliknite PDF/Ispis.</p><ul><li>Račun kupcu s PDV obračunom</li><li>Ponuda kupcu</li><li>Putni nalog vozaču</li><li>CMR / transportni dokument</li></ul><button onClick={()=>window.print()}>Ispiši trenutni ekran</button></div> }
function ExcelCenter(){ return <div className="card"><h3>Excel centar</h3><p>Svaki modul ima CSV/Excel gumb. Izvoz je lokalni CSV kompatibilan s Excelom.</p><p>Podržano za flotu, vozače, kupce, prijevoze, fakture, gorivo, servise, GPS, tahograf, plaće, CMR i 150 poslovnih funkcija.</p></div> }
function Features150({setToast}:any){ const [mods,setMods]=useState<Row[]>([]),[mid,setMid]=useState(1),[rows,setRows]=useState<Row[]>([]),[edit,setEdit]=useState<Row|null>(null); useEffect(()=>{api('/feature-modules').then(setMods)},[]); async function load(id=mid){setRows(await api('/feature-records/'+id))} useEffect(()=>{load().catch((e:any)=>setToast(e.message))},[mid]); const mod=mods.find(m=>m.id===mid); async function save(r:Row){try{const payload={title:r.title,status:r.status,priority:r.priority,amount:r.amount,due_date:r.due_date,data:{opis:r.opis,odgovorna_osoba:r.odgovorna_osoba,rizik:r.rizik,napomena:r.napomena}}; await api('/feature-records/'+(r.id?r.id:mid),{method:r.id?'PUT':'POST',body:JSON.stringify(payload)});setEdit(null);await load();setToast('Funkcijski zapis spremljen.')}catch(e:any){setToast(e.message)}} async function del(id:string){if(confirm('Obrisati zapis?')){await api('/feature-records/'+id,{method:'DELETE'});await load();}}
 return <><div className="toolbar"><select value={mid} onChange={e=>setMid(Number(e.target.value))}>{mods.map(m=><option key={m.id} value={m.id}>{m.id}. {m.name} — {m.category}</option>)}</select><button onClick={()=>setEdit({status:'open',priority:'normal'})}>+ Novi zapis</button></div><div className="card"><h3>{mod?.name}</h3><p>{mod?.description}</p><div className="kpis small"><K label="Kategorija" val={mod?.category}/><K label="Zapisa" val={rows.length}/><K label="Otvoreno" val={rows.filter(r=>r.status!=='closed').length}/><K label="Vrijednost" val={money(rows.reduce((s,r)=>s+Number(r.amount||0),0))}/></div></div><div className="card tableWrap"><table><thead><tr><th>Naslov</th><th>Status</th><th>Prioritet</th><th>Iznos</th><th>Rok</th><th>Akcije</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{r.title}</td><td>{r.status}</td><td>{r.priority}</td><td>{money(r.amount)}</td><td>{date(r.due_date)}</td><td><button onClick={()=>setEdit({...r,...(r.data||{})})}>Uredi</button><button className="danger" onClick={()=>del(r.id)}>Briši</button></td></tr>)}</tbody></table></div>{edit&&<FeatureForm row={edit} onClose={()=>setEdit(null)} onSave={save}/>}</> }
function FeatureForm({row,onClose,onSave}:any){ const [f,setF]=useState<Row>(row); return <div className="modal"><form className="modalCard" onSubmit={e=>{e.preventDefault();onSave(f)}}><div className="modalHead"><h2>Poslovna funkcija</h2><button type="button" onClick={onClose}>✕</button></div><div className="formGrid"><label>Naslov<input required value={f.title||''} onChange={e=>setF({...f,title:e.target.value})}/></label><label>Status<select value={f.status||'open'} onChange={e=>setF({...f,status:e.target.value})}>{['open','in_progress','waiting','closed'].map(x=><option key={x}>{x}</option>)}</select></label><label>Prioritet<select value={f.priority||'normal'} onChange={e=>setF({...f,priority:e.target.value})}>{['low','normal','high','critical'].map(x=><option key={x}>{x}</option>)}</select></label><label>Iznos<input type="number" value={f.amount||0} onChange={e=>setF({...f,amount:e.target.value})}/></label><label>Rok<input type="date" value={f.due_date||''} onChange={e=>setF({...f,due_date:e.target.value})}/></label><label>Rizik<select value={f.rizik||'srednji'} onChange={e=>setF({...f,rizik:e.target.value})}>{['nizak','srednji','visok'].map(x=><option key={x}>{x}</option>)}</select></label><label>Opis<textarea required value={f.opis||''} onChange={e=>setF({...f,opis:e.target.value})}/></label><label>Odgovorna osoba<input value={f.odgovorna_osoba||''} onChange={e=>setF({...f,odgovorna_osoba:e.target.value})}/></label><label>Napomena<textarea value={f.napomena||''} onChange={e=>setF({...f,napomena:e.target.value})}/></label></div><div className="modalActions"><button type="button" onClick={onClose}>Odustani</button><button>Spremi</button></div></form></div> }

createRoot(document.getElementById('root')!).render(<App/>);
